### ISSUE TITLE
SNMPv3

### ISSUE THREAD

**Issue by stephenwvickers** [markabrahams/node-net-snmp#1]

**Comment by petitout** [comment]
+1

**Comment by menixator** [comment]
@stephenwvickers any status on this?

**Comment by stephenwvickers** [comment]
Nothing to report as of yet, it's been slow going so far.

**Comment by dwhelan** [comment]
V3 support would be awesome. Do you have an ETA on this?

**Comment by stephenwvickers** [comment]
Unfortunately not as yet.  I am committed to doing this, but it's been slow going with work and other things.

**Comment by markabrahams** [comment]
Hi Steve - I've added v3 support to the library and submitted pull request #53 for this.

I'm writing an app that controls a v3-only network, and I notice a few albeit older requests for this as well, so would be quite good to get it reviewed for a possible merge.  Cheers!

**Comment by markabrahams** [comment]
FYI @stephenwvickers - just added an important fix to PR #53 - for an occasional decrypt failure.

**Comment by markabrahams** [comment]
Should anyone want to test the SNMPv3 feature before a PR merge - and without wanting to mess around with git - just add this to your package.json:
"net-snmp": "https://github.com/markabrahams/node-net-snmp.git"

and "npm install"

There's only one new public API call added:
snmp.createV3Session(target, user, [options])

Documentation for the new call is at:
https://github.com/markabrahams/node-net-snmp

**Comment by markabrahams** [comment]
Added another fix to PR #53 for a very occasional decrypt last-byte-truncate condition.  Consistently walking the whole Net-SNMP agent MIB (1.3.6.1) without error with MD5/DES and SHA/DES authPriv now.

**Comment by markabrahams** [comment]
In a whirlwind of activity, @stephenwvickers has assigned ownership of this repository and the net-snmp NPM to me, PR #53 is merged now, and SNMPv3 is now available in the newly-published version 2.0.0 of the net-snmp NPM.

Although this isn't a breaking change - there's been only one API call added - it is a bump in SNMP protocol version support, and the code has undergone a significant amount of structural change to support this, so we've decided to bump the major version here.
