### ISSUE TITLE
subtree error when device response with "OID not increasing"

### ISSUE THREAD

**Issue by cesarmacias** [markabrahams/node-net-snmp#101]
Hi,

I make a snmpwalk to thousands of devices with subtree, but when the device response with the error "OID not increasing", the response of varbinds repeat the this value many many times, without a error to stop.

snmpwalk:

-bash-4.2$  snmpwalk -v 2c -c public 10.36.197.84  -On .1.3.6.1.4.1.4115.1.20.1.1.3.42.1.22
.1.3.6.1.4.1.4115.1.20.1.1.3.42.1.22.10001.1.4.192.168.0.5 = INTEGER: -76
.1.3.6.1.4.1.4115.1.20.1.1.3.42.1.22.10001.1.4.192.168.0.7 = INTEGER: -43
.1.3.6.1.4.1.4115.1.20.1.1.3.42.1.22.10001.1.4.192.168.0.8 = INTEGER: -69
.1.3.6.1.4.1.4115.1.20.1.1.3.42.1.22.10001.1.4.192.168.0.9 = INTEGER: -67
.1.3.6.1.4.1.4115.1.20.1.1.3.42.1.22.10001.1.4.192.168.0.9 = INTEGER: -67
Error: OID not increasing: .1.3.6.1.4.1.4115.1.20.1.1.3.42.1.22.10001.1.4.192.168.0.9
 >= .1.3.6.1.4.1.4115.1.20.1.1.3.42.1.22.10001.1.4.192.168.0.9

-bash-4.2$

subtree response:

       -67,
        -67,
        -67,
        -66,
        -66,
        -66,
        -66,
        -66,
        -66,
        -66,
        -66,
        -66,
        -66,
        -66,
        -66,
        -66,
        -66,
        -66,
        -66,
        -66,
        -66,
        -66,
        -66,
        -66,
        -66,
        -66,
        -66,
        -66,
        -66,
        -66,
        -66,
        -66,
        -66,
        -66,
        -66,
        -66,
        -66,
        -66,
        -66,
        -66,
        ... 92 more items ],

**Comment by markabrahams** [comment]
Hi @cesarmacias - if you could follow the guidelines in CONTRIBUTING.md on what to include in a bug report - that would be great.  In particular these points:
- Reduce the problem to a minimal reproducible example
- Post code
- Include packet captures

**Comment by markabrahams** [comment]
This issue has gathered all the interest of a term-deposit in a Japanese bank account.
