### ISSUE TITLE
Performance Comparison between Node-net-snmp and CLI Net-SNMP Utility

### ISSUE THREAD

**Issue by yeongwei** [markabrahams/node-net-snmp#103]
Hello There!

1. We recently run into frequent errors of RequestTimedOutError on a production system

2. While we are checking with the Networking team to find out what might have caused this. I did some measurement testing limited to the scope using `getNext` method

3. I found out that while using `getNext` after about 30 to 60 or so responses, there would be one response which takes about 3 minutes then follow by another 30 to 60 or so responses with normal duration then the cycle repeats itself

4. I then used the CLI `snmpgetnext` from `1:net-snmp-utils-5.7.2-43.el7_7.3.x86_64 : Network management utilities using SNMP, from the NET-SNMP project` by feeding it with the list of OIDs that I used in point 3. The response time is fine even running multiple iterations

5. I then switched to use `subtree` as an alternative, but the result still is frequent RequestTimedOutError 

6. Could you suggest if there is anywhere else I could look into? Or if there is something I am missing?

Thank you very much in advance!

**Comment by markabrahams** [comment]
Hi @yeongwei - if you could follow the guidelines in CONTRIBUTING.md on what to include in a bug report - that would give the greatest chance of you or someone else being able to reproduce and diagnose your problem. In particular these points:
- Reduce the problem to a minimal reproducible example
- Post code
- Include packet captures (for your particular example comparing captures from Net-SNMP and the node-net-snmp library would be a useful troubleshooting tool)

**Comment by yeongwei** [comment]
Hi @markabrahams,

1. I apologize for not providing sufficient information

2. Our team has got back to us that here was a Firewall failed over and the policies got reverted.

3. We can close this ticket,

Thank you very much.

**Comment by markabrahams** [comment]
Thanks for closing the loop on this @yeongwei - much appreciated!
