### ISSUE TITLE
async session.table ?

### ISSUE THREAD

**Issue by almadrasa** [markabrahams/node-net-snmp#104]
i want the 2 line to wait until the 1 line finsh completly his job
![image](https://user-images.githubusercontent.com/34221874/88468483-602e5e80-cedc-11ea-9a29-705e560e09bd.png)

**Comment by markabrahams** [comment]
Hi @almadrasa - it's great that you're using the library, and have posted code to illustrate your problem.

The workings of asynchronous callbacks is a fundamental part of Node.js programming, so it's well worth the investment researching and building an understanding of this concept with articles such as this:
https://javascript.info/callbacks

Particularly look at the "Callback in callback" section - as that shows the structure of the solution you're looking for.
