### ISSUE TITLE
[question] get raw byte values

### ISSUE THREAD

**Issue by nyotiemon** [markabrahams/node-net-snmp#105]
are there any way to read the raw buffer values on Session.get for types other than OctetString from varbind result?
something like
```
var varbind = {
    oid: "1.3.6.1.2.1.1.4.0",
    type: snmp.ObjectType.Integer,
    value: 500000000,
    raw: new Buffer("1dcd6500", "hex");
};
```

**Comment by markabrahams** [comment]
Hi @nyotiemon - no there isn't access to a raw buffer for varbinds with ObjectTypes that are intended as higher-level data e.g. integers.
