### ISSUE TITLE
Failure to read Synology's OID

### ISSUE THREAD

**Issue by ondras** [markabrahams/node-net-snmp#106]
node-net-snmp:
```
 $ node snmp-get nas.home public 2c 1.3.6.1.4.1.6574.1.2
NoSuchInstance: 1.3.6.1.4.1.6574.1.2
```

python net-snmp:
```
$ snmpwalk -v 2c -c public nas.home 1.3.6.1.4.1.6574.1.2
SNMPv2-SMI::enterprises.6574.1.2.0 = INTEGER: 44
```

The OID in question is Synology's NAS/DSM temperature reading. The SNMP server is not providing any logging facility, so it is kinda difficult to see what is going on. Will report if I manage to extract more details.

**Comment by unchained-za** [comment]
Hi, 
You will have to do the get on the .0 instance as seen on the snmpwalk. 

Regards

**Comment by ondras** [comment]
Hi @unchained-za,

thanks a lot for explanation!
