### ISSUE TITLE
session.subtree receives only 100 records

### ISSUE THREAD

**Issue by AliakseyShapel** [markabrahams/node-net-snmp#107]
Hi!
Let me first say big Thanks for your work! Its amazing package!

I have found, that `session.subtree (oid, [maxRepetitions], feedCallback, doneCallback)` reads only 100 records maximum, not depending of maxRepetitions. When I tried to use another snmp package, it did read all 200 records. I was looking the source code, but could`n find a problem.

Protocol Snmp version 2c

**Comment by markabrahams** [comment]
Hi @AliakseyShapel - thanks for that - glad that you're finding the library helpful!

I've just tested with the example subtree code that comes with the library against a Linux Net-SNMP agent:
`node example/snmp-subtree.js -v 2c -c public localhost 1.3.6.1`

and it reads the entire (25,197 object) MIB fine.

To isolate the problem further, if you could follow the guidelines in CONTRIBUTING.md on what to include in a bug report - that would be helpful. In particular these points:
- Reduce the problem to a minimal reproducible example
- Post code

**Comment by AliakseyShapel** [comment]
Hello. I have written minimal code to get subtree. Yes, method returned all 5516 records in bulks of 100 records each. Earlier I was trying to promisify the subtree method and it was returning my promise after 100 records. So, issue is just in my knowledge, not in the package :(. 
I`m very sorry about raising this issue. 
Still I think your package is wonderful!

Here is my code. It is logging just 100 in console. I will be glad if you suggest me the way I can adjust it to log all 5516 records. And sure, I`ll look the way I can do it myself ;)

```
const snmp = require('net-snmp');

const subtree = (ip, community, oid) => {
  const promise = new Promise((resolve, reject) => {
    const session = snmp.createSession(ip, community, { version: snmp.Version2c });
    session.subtree(
      oid,
      (varbinds) => {
        const oidsData = [];
        for (var i = 0; i < varbinds.length; i++) {
          if (snmp.isVarbindError(varbinds[i])) {
            console.log(snmp.varbindError(varbinds[i]));
          } else {
            oidsData.push({ oid: varbinds[i].oid, value: varbinds[i].value });
          }
        }
        resolve(oidsData);
      },
      (error) => {
        reject(error);
      }
    );
  });
  return promise;
}

const init = async () => {
  const OID = '1.3.6.1.4.1.4249.1.9016';
  const varbinds = await subtree('192.168.255.2', 'public', OID);
  console.log(varbinds.length);
}

init();
```

**Comment by markabrahams** [comment]
Hi @AliakseyShapel - thanks for following up.

Here's the code that does what you're after (I've commented out the parts from your original code that need changing):

`const snmp = require('net-snmp');

const subtree = (ip, community, oid) => {
  const promise = new Promise((resolve, reject) => {
    const session = snmp.createSession(ip, community, { version: snmp.Version2c });
    const oidsData = [];
    session.subtree(
      oid,
      (varbinds) => {
        //const oidsData = [];
        for (var i = 0; i < varbinds.length; i++) {
          if (snmp.isVarbindError(varbinds[i])) {
            console.log(snmp.varbindError(varbinds[i]));
          } else {
            oidsData.push({ oid: varbinds[i].oid, value: varbinds[i].value });
          }
        }
        //resolve(oidsData);
      },
      (error) => {
        //reject(error);
        if ( error ) {
            reject(error);
        } else {
            resolve(oidsData);
        }
      }
    );
  });
  return promise;
}

const init = async () => {
  const OID = '1.3.6.1.4.1.4249.1.9016';
  const varbinds = await subtree('localhost', 'public', OID);
  console.log(varbinds.length);
}

init();
`

**Comment by AliakseyShapel** [comment]
That solves the problem! Thank you very much!
