### ISSUE TITLE
Incorrect `namespace` values for SNMPv2-SMI `org`

### ISSUE THREAD

**Issue by bentorkington** [markabrahams/node-net-snmp#108]
ModuleStore seems to generate an incorrect value for the `namespace` property for the `iso.org` OID. The incorrect value reported is `iso..org`. The expected value is `iso.org`

### Version 
net-snmp 2.7.1

### To reproduce
```js
const snmp = require('net-snmp');

const store = snmp.createModuleStore();
var jsonModule = store.getModule('SNMPv2-SMI');

console.log(jsonModule.org);
```

### Sample output
```
  org: {
    ObjectName: 'org',
    ModuleName: 'SNMPv2-SMI',
    'OBJECT IDENTIFIER': 'iso 3',
    OID: '1.3.',
    NameSpace: 'iso..org'
  },
```

**Comment by markabrahams** [comment]
Hi @bentorkington - thanks for reporting this, and also for including code for a minimal reproduction.  I've fixed this now and published the fix in version 2.7.5 of the npm.
