### ISSUE TITLE
Dependencies issues

### ISSUE THREAD

**Issue by bastianhilton** [markabrahams/node-net-snmp#114]
hello i'm setting a project using this module and i'm getting the following error message:

These dependencies were not found:

* dgram in ./node_modules/net-snmp/index.js
* fs in ./node_modules/net-snmp/lib/mib.js

To install them, you can run: npm install --save dgram fs

not sure how use the module if dgram and fs are deprecated and it requires them, i can subsitute dgram with dgramx but for fs it doesn't subsitute properly with fs-extra.

**Comment by Azerothian** [comment]
dgram and fs are native nodejs libraries, if you are missing these you must not be running under node

**Comment by markabrahams** [comment]
Hi @bastianhilton - if you could follow the guidelines in CONTRIBUTING.md on what to include in a bug report - that would be great. In particular these points:
- Reduce the problem to a minimal reproducible example
- Post code

**Comment by markabrahams** [comment]
This issue is about as static as the static that fills my attic on Channel Z.
