### ISSUE TITLE
Invalid identifier for Object identifier which start with leading dot.

### ISSUE THREAD

**Issue by PatelMaulik31** [markabrahams/node-net-snmp#116]
I am trying session.trap method with constructor(typeorvarOID, VarOIDS, options,callback).
and I am  passing Object identifier with leading dot then its giving error like invalid Object Identifier.
If this is not an issue then please specify how to handle Object Identifier with leading dot

**Comment by markabrahams** [comment]
Hi @PatelMaulik31.  Simply strip the leading dot.
