### ISSUE TITLE
SNMPV3 encryption timeout

### ISSUE THREAD

**Issue by ASH3xC0d3** [markabrahams/node-net-snmp#119]
Mark,

First of all, thanks for your great work, making this project.

I have been testing the SNMPV3 code and implementing this in Node-Red.
Whilst testing I found that if the encryption protocol or encryption passphrase is incorrect, the code does not return an Error but instead times out.
The authentication protocol and passphrase work as described and does return an Error if either of them is incorrect.

Call: `sessions[V3sessionKey] = snmp.createV3Session(host, user, { port:port, timeout:(timeout || 5000) });`
where user is made up of the following info (apology, this is node-red code)
`			var user = {
				name: "test",
				level: snmp.SecurityLevel.authPriv,
				authProtocol: snmp.AuthProtocols.md5,
				authKey: "test1234test",
				privProtocol: snmp.PrivProtocols.des,
				privKey: "privycouncil"
			};
`
When privProtocol or privKey are incorrect, the code times out after 5 seconds and returns `RequestTimedOutError: Request timed out.`
If required, I can create a wireshark capture.

Please 'tap' me on my electronic fingers as I have not provided enough information.

**Comment by markabrahams** [comment]
Hi @ASH3xC0d3 - thanks - glad you've found the project useful.

First off - the CONTRIBUTING.md guideline "Reduce the problem to a minimal reproducible example" outlines the importance of doing some work to narrow the code you post to a minimal example.  Your goal is to enable the project contributor to instantly reproduce the problem.  That means I should be able to copy-paste your code, and get the same error/condition that you're reporting.  Although you provided code, it was a snippet of someone else's, wasn't minimal or complete, and took me about 15 minutes to fill in the gaps to try to reproduce the condition.  It doesn't matter how trivial you think your example is, or how well you think you've explained it, always post copy-paste-able, runnable code.

In this case, a Wireshark capture is required, as it will provide the key to what's going on - so you'll need to post that as well.

Either:
(1) The agent you're testing against isn't responding within 5 seconds, in which case the library code (assuming you're doing a session.get or something like that - you haven't posted that part) is doing exactly what it should, OR
(2) The agent you're testing against is responding within 5 seconds, and the library code is not reporting the response.

A Wireshark capture will reveal which of these it is.  If I was a betting man, I'd put money on (1).

**Comment by ASH3xC0d3** [comment]
Mark,

Thank you for your response and again my apology for my ignorance.
I am new with this type of code and just trying to give my contribution to the node-red forum, promoting and using your code.
There is a valid call and a call that should fail. call initiated from 192.168.0.58, response from 192.168.0.39....
Please find attached the wireshark code. I do a valid request to 192.168.0.39 and see the reply `15	1.892909	192.168.0.39	192.168.0.58	SNMP	191	encryptedPDU: privKey Unknown`.
I had another look through the code and we capture error for V2c and V3 as per your documents
`                   openV3Session(host, user, uid, node.timeout).get(oids.split(","), function (error, varbinds) {
                        if (error) {
                            node.error(error.toString(), msg);
                        }
                        else {
                            for (var i = 0; i < varbinds.length; i++) {
                                if (snmp.isVarbindError(varbinds[i])) {
                                    node.error(snmp.varbindError(varbinds[i]), msg);
                                }
                                else {
                                    if (varbinds[i].type == 4) { varbinds[i].value = varbinds[i].value.toString(); }
                                    varbinds[i].tstr = snmp.ObjectType[varbinds[i].type];
                                }
                            }
`
I already confirmed other error codes like authentication errors where being returned and captured, but this appears not to be captured. Don't get me wrong, the issue might still be on my side, as I am not as knowledgeable with the code, as I would like to be, so again, 'tap' me on my electronic fingers if I am acting ignorant or just plain stupid.

Thanks again, learning hard and fast, and that is the only way to learn ;-)

[snmp.zip](https://github.com/markabrahams/node-net-snmp/files/5213940/snmp.zip)

**Comment by markabrahams** [comment]
Hi @ASH3xC0d3 - it seems you've underestimated the importance of supplying a minimal reproducible example, as you've provided more NodeRed code that is neither minimal nor complete.  Providing a minimal reproducible example is of incredible service to the contributor helping with your problem, and the community that might be gaining insight from reading the issue report.

These articles underscore the importance of this, as well as how to go about producing a good minimal reproducible example:
https://stackoverflow.com/help/minimal-reproducible-example
https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

In your case, the minimal reproducible example would be code to:
1. require the 'net-snmp' library
2. create a user object with correct authentication key, but incorrect privacy key
3. create a v3 session with that user
4. issue a session.get

Remember, someone should be able to copy-paste the code you supply, and run it to reproduce the condition.

Thanks for supplying the Wireshark capture.  One problem with it is that you've mixed a working and non-working example into a single capture, and so the person helping you is left to guess as to what packets might belong to the working example and what packets might belong to the non-working example.  Also, they're left guessing as to the exact keys used for each interaction e.g. I tried using the keys in your original post to decode the capture, but they didn't decode any of the encrypted packets.

So for your next post:
- Copy-paste your minimal reproducible example of the problem as described in this post.  Use Github's "Insert code" feature to format your code correctly in your post.
- Provide the Wireshark capture when running the exact code that you post - which will contain only the problem scenario.  Then there's no guessing required.

You got this - I believe in you!

**Comment by gavinaiken** [comment]
I have noticed the same behaviour - incorrect auth passphrase gives an error, whereas incorrect encryption (privacy) passphrase gives a timeout. However the behaviour of the library corresponds to the behaviour of the Net-SNMP command line tools, which makes me believe that this is a limitation of the protocol, not a problem with this library. You also get the same behaviour with version 2c of the protocol and an incorrect community string, i.e. a timeout rather than an error.

Here's what I see using the command line tools:

```
# snmpget -v 3 -l authPriv -u MYUSER -a md5 -A <CORRECT> -x aes -X <CORRECT> 172.27.255.1 1.3.6.1.2.1.1.5.0
SNMPv2-MIB::sysName.0 = STRING: <hostname>

# snmpget -v 3 -l authPriv -u MYUSER -a md5 -A <WRONG> -x aes -X <CORRECT> 172.27.255.1 1.3.6.1.2.1.1.5.0
snmpget: Authentication failure (incorrect password, community or key)

# snmpget -v 3 -l authPriv -u MYUSER -a md5 -A <CORRECT> -x aes -X <WRONG> 172.27.255.1 1.3.6.1.2.1.1.5.0
Timeout: No Response from 172.27.255.1.
```

**Comment by sean-lawless** [comment]
Yes, the error is found in the response, but if the response decryption fails because of a key mismatch, it is discarded. Thus no error and an eventual timeout. It can't work otherwise or it would be vulnerable to Denial Of Service attacks.

**Comment by markabrahams** [comment]
Yes that's correct @sean-lawless.

@ASH3xC0d3 - if the library is not seeing returned traffic from the agent, then a timeout is expected behaviour.
