### ISSUE TITLE
RequestInvalidError: Unknown PDU type '0' in request

### ISSUE THREAD

**Issue by pluzzke** [markabrahams/node-net-snmp#121]
I regularly get the error "RequestInvalidError: Unknown PDU type '0' in request". It does not trigger for all the messages but only some messages.

The AgentXPdu looks like this after parsing the buffer:
AgentXPdu {
  version: 0,
  pduType: 0,
  flags: 0,
  sessionID: 38400,
  transactionID: 0,
  packetID: 327680,
  payloadLength: 100925440
}

I can't make any sence of the buffer unfortunately so i could not say if the received message was just invalid. Hopefully this is enough information to fix the problem. Let me know how to provide more information if you need more information.

**Comment by markabrahams** [comment]
Hi @pluzzke.  Either:
(1) Your sub-agent is receiving an invalid AgentX request and the library is reporting this exactly as it should OR
(2) Your sub-agent is receiving a valid AgentX request and the library is incorrectly reporting this as invalid.

By following the CONTRIBUTING.md guideline to include a packet capture (this needs to be a capture at the time the error is reported), I (or you!) will be able to determine which of these two it is.  If I were a betting man, my money would be on (1).

**Comment by markabrahams** [comment]
This issue is so neglected, even the Care Bears wanted nothing to do with it.
