### ISSUE TITLE
add option to set binding for agent

### ISSUE THREAD

**Issue by jumoog** [markabrahams/node-net-snmp#123]
Per default the agent binds to the any IP.
In my case i have several network cards and the wrong one is always connected. 

https://github.com/markabrahams/node-net-snmp/blob/bdf9e6a7d29a5d435a40db135643a1f9a50717e8/index.js#L2665

**Comment by markabrahams** [comment]
Hi @jumoog - thanks for the PR here!  I've merged this into master and published in version 2.9.3 of the npm.
