### ISSUE TITLE
document text don't match its demo code readme.doc 

### ISSUE THREAD

**Issue by 1000copy** [markabrahams/node-net-snmp#125]
https://www.npmjs.com/package/net-snmp#sessiongetbulk-oids-nonrepeaters-maxrepetitions-callback

when this paragraph talk about function `getbulk` ,but demo code not for `getbulk`.instead for `getnext`

**Comment by markabrahams** [comment]
Thanks @1000copy - fixed in master and fix published in version 2.9.4 of the npm.
