### ISSUE TITLE
ResponseInvalidError: Failed to decrypt PDU

### ISSUE THREAD

**Issue by TheEccentric007** [markabrahams/node-net-snmp#130]
Error is thrown from callback function in **snmp.createReceiver** 

using the SNMPv3 options
  const user = {
    name: "user",
    level: snmp.SecurityLevel.authPriv,
    authProtocol: snmp.AuthProtocols.sha,
    authKey: "theauthkey",
    privProtocol: snmp.PrivProtocols.aes,
    privKey: "theyencryptkey",
  };

  const option = {
    port: 8888,
    disableAuthorization: false,
    transport: "udp4",
    accessControlModelType: snmp.AccessControlModelType.None,
    address: null,
    engineID: "10.10.10.10",
  };

Error Thrown:

{0] { ResponseInvalidError: Failed to decrypt PDU: TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be one of type string, TypedArray, or DataView. Received type undefined
[0]     at Message.decryptPdu (/var/www/e-map-indicator/node_modules/net-snmp/index.js:1374:16)
[0]     at Message.processIncomingSecurity (/var/www/e-map-indicator/node_modules/net-snmp/index.js:1334:15)
[0]     at Function.Listener.processIncoming (/var/www/e-map-indicator/node_modules/net-snmp/index.js:2723:18)
[0]     at Receiver.onMsg (/var/www/e-map-indicator/node_modules/net-snmp/index.js:2955:25)
[0]     at Socket.emit (events.js:198:13)
[0]     at UDP.onMessage [as onmessage] (dgram.js:628:8)
[0]   name: 'ResponseInvalidError',
[0]   message:
[0]    'Failed to decrypt PDU: TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be one of type string, TypedArray, or DataView. Received type undefined' }

**Comment by TheEccentric007** [comment]
const user = {
    name: "user",
    level: snmp.SecurityLevel.authPriv,
    authProtocol: snmp.AuthProtocols.sha,
    authKey: "theauthkey",
    privProtocol: snmp.PrivProtocols.aes,
    privKey: "theyencryptkey",
  };

  const option = {
    port: 8888,
    disableAuthorization: false,
    transport: "udp4",
    accessControlModelType: snmp.AccessControlModelType.None,
    address: null,
    engineID: "10.10.10.10",
  };

**Comment by markabrahams** [comment]
Hi @TheEccentric007 - if you could follow the guidelines in CONTRIBUTING.md on what to include in a bug report, that would provide the information needed to troubleshoot this. In particular these points:
- Reduce the problem to a minimal reproducible example (i.e. supply code for a complete program that someone can copy-paste and run)
- Include packet captures 

In this case, you'll also need to include the client code (or Net-SNMP CLI command) used to generate the trap or inform in question.

Supplying this information would reveal whether:
(1) Your receiver is receiving an invalid trap or inform and the library is reporting this exactly as it should OR
(2) Your receiver is receiving a valid trap or inform and the library is incorrectly reporting this as invalid.

If I were a betting man, my money would be on (1).

**Comment by TheEccentric007** [comment]
@markabrahams thanks a lot for the response. Due to some reasons, I cannot supply sufficient information to meet up point one. 

If I were a betting man, my money would be on you thus (1).  

I will refer back to Northbound on (1)
