### ISSUE TITLE
Help async/await

### ISSUE THREAD

**Issue by olishr** [markabrahams/node-net-snmp#133]
Can someone please help me. I want to run multiple .subtree calls, wait for all to finish and then call "request", or call "request" after each .subtree is finished and then clear variable "o" for the next call.
Example:

```
var o = {};
o = []; 

var oids = [
  "1.3.6.1.4.1.14179.2.2.1.1.1",
  "1.3.6.1.4.1.14179.2.2.1.1.19",
  "1.3.6.1.4.1.14179.2.2.1.1.22",
  "1.3.6.1.4.1.14179.2.2.1.1.16",
  "1.3.6.1.4.1.14179.2.2.1.1.30",
  "1.3.6.1.4.1.14179.2.2.1.1.3"
];

function doneCb (error) {
  request.post({
    url: 'https://www.somepage.com/api/dosomething.php',
    body: o,
    json: true
  }, function(error, response, body) {
    console.log(body);
    o = [];
  });
  console.log(o);

    if (error)
        console.error (error.toString ());
      }

function feedCb (varbinds){
  for (var i = 0; i < varbinds.length; i++)
  {
    if (snmp.isVarbindError (varbinds[i]))
        console.error (snmp.varbindError (varbinds[i]));
    else
      {
        var data = {
          oid: (varbinds[i].oid).replace(oid[i], '').toString(),
          value: (varbinds[i].value).toString()
      };
      o.push(data);      
      }
    }
  }
  var maxRepetitions = 1;

  function pozovi(){
    for (i=0; i<=5;i++) {
    session.subtree(oids[i], maxRepetitions, feedCb, doneCb);
  }
  }
  setInterval(pozovi, 5000);
```

**Comment by unchained-za** [comment]
Hi 

A question first, why do you use maxRepetition = 1? As it will use getbulk if your snmp version is 2c or 3, it will be more efficient to make it bigger. My most efficient default value thus far was about 50 in various situations. 

Then, you can also put the subtree call in a function that returns a promise, push a whole batch of these promises with a foreach or whatever into an array and wait for Promise.allSettled or something to process the results. If there are many of these calls to the same IP, I'd suggest that you rather a use queue where you can control the number of simultaneous requests. Issuing too many simultaneous requests to a single device or through a specific switch may cause packet drop as SNMP is usually a fairly low priority protocol and/or service and most hosts. 

BTW, I'm currently also working on monitoring WLCs and APs, unfortunately having to deal with a simulator for testing. 

Regards 

PS: I may be slow in responding or forget to do it as work under extreme pressure and for very long hours at the moment to finish a project, still learning various aspects and tools of the project too. 

PPS: Here follows a rough idea, didn't check the syntax or anything else, just the quick sample to consider as an idea - needs lodash: npm i lodash 

var _ = require('lodash'); 
var o = {};
o = []; 

var oids = [
  "1.3.6.1.4.1.14179.2.2.1.1.1",
  "1.3.6.1.4.1.14179.2.2.1.1.19",
  "1.3.6.1.4.1.14179.2.2.1.1.22",
  "1.3.6.1.4.1.14179.2.2.1.1.16",
  "1.3.6.1.4.1.14179.2.2.1.1.30",
  "1.3.6.1.4.1.14179.2.2.1.1.3"
]; 
var maxRepetitions = 20; 
function doSnmp(session, oid) 
{ 
return new Promise(function(resolve, reject) 
{ 
function doneCb (error) { 
if (error) return reject(error); return resolve(o); 
}

function feedCb (varbinds){
  for (var i = 0; i < varbinds.length; i++)
  {
    if (snmp.isVarbindError (varbinds[i]))
        console.error (snmp.varbindError (varbinds[i]));
    else
      {
        var data = {
          oid: (varbinds[i].oid).replace(oid[i], '').toString(),
          value: (varbinds[i].value).toString()
      };
      o.push(data);      
      }
    }
  } 
}); 
} 


var promises = []; 
function pozovi(){ 
_.forEach(oids, function(iod){ 
promises.push(doSnmp(session, oid); 
}); 
Promise.allSettled(function(res) 
{ 
for (var i = 0; i < res.length; i++) 
{ 
if (res[i].status.error) continue; // or process/display error and then skip the rest 
request.post({
           url: 'https://www.somepage.com/api/dosomething.php',
           body: res[i].value,
           json: true
       }, function(error, response, body) {
       console.log(body);
  }); 
} 

setInterval(pozovi, 5000);

**Comment by markabrahams** [comment]
Thanks for replying to that @unchained-za!
