### ISSUE TITLE
I have translated your document  to Chinese

### ISSUE THREAD

**Issue by 1000copy** [markabrahams/node-net-snmp#134]
Hi there. I really love and apply your module to my application. I have translated your manual into Chinese. The location is (here)[https://segmentfault.com/a/1190000037458196] ,

May I provide you with PR and give you the original markdown file, or you can add a link to your readme.md to make it easier for Chinese users to use?

**Comment by markabrahams** [comment]
Hi @1000copy - wow, that's a great effort!  Yes, if you submit a PR with the markdown file, I'll merge it.

**Comment by markabrahams** [comment]
Thanks @1000copy - I've merged #135 and published in version 2.9.7 of the npm.
