### ISSUE TITLE
Subagent cannot connect to master agent based on example

### ISSUE THREAD

**Issue by neonmura** [markabrahams/node-net-snmp#137]
Hi,
I have a question related to sub-agents and master agents. I've been following/testing node-net-smtp from the examples, and tried to connect a subagent to a master agent created based on the examples. As I understand port 705 is used for subagents, but when connecting, it returns ECONNREFUSED. I suspect that the master agent is not listening on port 705, but how do I enable it in the master agent options? Is there setting for that?

Thanks for any help! ^_^

**Comment by markabrahams** [comment]
Hi @neonmura - you're correct in that this is a problem with your master agent, and not the node-net-snmp subagent.  Either you're not running a master agent, or the master agent you're running isn't listening on TCP port 705.  So your fix here is to configure your master agent to listen to AgentX requests on TCP port 705.

What software are you running for your master agent?

**Comment by neonmura** [comment]
Hi @markabrahams,
Thanks for replying. 
Since I am quite new to snmp so I am starting to experiment with only using node-net-smtp. The master is an agent created after the agent examples. 

So I am guessing there might be some options that I am missing when creating the agent. 
In my case both master and sub-agent are using node-net-snmp.

**Comment by markabrahams** [comment]
The node-net-snmp library doesn't currently contain AgentX master agent support, only AgentX subagent support.  You'll have to find a master agent to run if you want to run the node-net-snmp subagent example.

For example, Net-SNMP's agent (snmpd) can run an AgentX master with these lines of configuration in the config file (snmpd.conf):
```
master agentx
agentXSocket tcp:localhost:705
```

**Comment by neonmura** [comment]
I see. Thanks for clarifying this. I’ll use snmpd to continue with the subagent testing then. :-)
Thank you!
