### ISSUE TITLE
The UNITS clause of an OID is not processed correctly

### ISSUE THREAD

**Issue by robertdeml** [markabrahams/node-net-snmp#142]
Create a test MIB file:
TEST-MIB DEFINITIONS ::= BEGIN

IMPORTS
  MODULE-IDENTITY, enterprises 	FROM SNMPv2-SMI
  TEXTUAL-CONVENTION 			FROM SNMPv2-TC;

testEnterprises MODULE-IDENTITY ::= { enterprises 999999 }

test1 OBJECT-TYPE
  UNITS "MyUnits"
  MAX-ACCESS read-only
  STATUS current
  DESCRIPTION
  "Test OID"
  ::= { testEnterprises 100 }

END

Create a test program: (I'm using typescript)
import snmp from "net-snmp";

var store = snmp.createModuleStore();
store.loadFromFile("units-mib.txt");
let data = store.getModules(false);
console.log("we should find the Units:" + data["TEST-MIB"].test1.UNITS);

Run the program.
Actual results: The Units clause it not found.
Expected Results: It should find MyUnits as the Units clause.

The patch is to replace mib.js:372-375 with this:
                                            if (MARCO['TYPE NOTATION'][notation] == null) {
                                                //then look up the value from the MACRO Root
                                                key = MARCO[notation]['MACRO'].replace(/"/g, ''); // remove the quotes.
                                            }

The problem is that when the SNMPv2-SMI.mib is being parsed, it finds 'UnitsPart', and copies the "UNITS" to the MACRO object, but it keeps the quotation marks.  I don't think the quotations should be stripped there because it is still parsing the other macros that might be nested.

My patch is inserted when it is filling out the keychain.  When it runs into a TYPE NOTATION that is null, then it looks for that property in the root MARCO object.  But it needs just the text and that is found in the MACRO property but it is still the quoted string.

So the change is to step into the root-notation property's MACRO property and remove the quotes.

This should also fix the other Type Notations that are defined as macros, such as REFERENCE, INDEX, and DEFVAL.

**Comment by markabrahams** [comment]
Hi @robertdeml - thanks for the report and for the fix.  I've made this change now, and published in version 2.10.1 of the npm.
