### ISSUE TITLE
Keep collection data from using same session

### ISSUE THREAD

**Issue by vitorvr** [markabrahams/node-net-snmp#149]
I'm new to `node-net-snmp` and I'm implementing an app to collect data from temperature sensors.
I'm already able to connect to the sensor and collect data using `snmp.createSession` and `session.get`.
Is there a way to keep this connection up collection data or I need to implement something using `setInterval` for example to run `session.get` every 5 seconds?

Thanks!

**Comment by markabrahams** [comment]
Hi @vitorvr  - the library functions do not offer periodic polling functionality by design.  So, as you say, you need to implement the periodic polling in your application, using `setInterval` for example.
