### ISSUE TITLE
Response with many "End mib view"

### ISSUE THREAD

**Issue by IvanAguiar** [markabrahams/node-net-snmp#150]
Hello,

Implementing a SNMP Agent, when I do a snmpwalk using a C implementation on linux (net-snmp), I got:

ifIndex.1 = INTEGER: 1
ifIndex.2 = INTEGER: 2
ifDescr.1 = STRING: "lo"
ifDescr.2 = STRING: "eth0"
ifType.1 = INTEGER: softwareLoopback(24)
ifType.2 = INTEGER: 99
ifType.2 = No more variables left in this MIB View (It is past the end of the MIB tree)
ifType.2 = No more variables left in this MIB View (It is past the end of the MIB tree)
ifType.2 = No more variables left in this MIB View (It is past the end of the MIB tree)
ifType.2 = No more variables left in this MIB View (It is past the end of the MIB tree)

The question: Is right these last four lines in output?
If not, how could I fix that?

**Comment by markabrahams** [comment]
That output is expected if that is indeed the end of your agent's MIB.  It looks like you're using the example/snmp-agent.js example, in which case it is.
