### ISSUE TITLE
UCD-SNMP-MIB only partially gets loaded

### ISSUE THREAD

**Issue by DineshDevaraj** [markabrahams/node-net-snmp#155]
After implementing the work-around mentioned in [Issue#151](https://github.com/markabrahams/node-net-snmp/issues/151#issuecomment-755275115) I was able to load UCD-SNMP-MIB, but it only gets loaded partially. I see only one table in the list of table providers.

**# code** 

```

let snmp = require("net-snmp")
let mibStore = snmp.createModuleStore()

mibStore.loadFromFile("/root/programs/nodejs/snmp-agent/mib-files/UCD-SNMP-MIB.mib")

let moduleNames = mibStore.getModuleNames()
// console.log("Module name : ", moduleNames)

let providers = mibStore.getProvidersForModule(moduleNames[0])
// console.log("Providers : ", providers)

for (I in providers) {
	if ("tableName" in providers[I]) {
		console.log(providers[I].tableName, providers[I].name)
	}
}

```

**# output**
```

root@c8c1c6a106c2:~/programs/nodejs/snmp-agent# node load-ucd-mib.js
logMatchTable logMatchEntry
root@c8c1c6a106c2:~/programs/nodejs/snmp-agent#

```

**Comment by markabrahams** [comment]
Hi @DineshDevaraj - this was due to not parsing the tab character correctly.  I've fixed this now in master and published the fix in version 3.0.6 of the npm.
