### ISSUE TITLE
Feature request: sub-types

### ISSUE THREAD

**Issue by derrell** [markabrahams/node-net-snmp#156]
At present, the only "constraint" is enumerations. This issue requests that a new constraint be added, which is sub-types, as described in [RFC-2578, Appendex A](https://tools.ietf.org/html/rfc2578#page-40). A possible implementation, in the provider's `constraints` member, is an array of maps, where each map contains members `min` and `max`, each optional (but at least one must be defined in a range). For example, a table column might be defined like this:

```
      {
        "number": 3,
        "name": "numPlayers", // in range [4-9], or greater than 11 (inclusive)
        "type": 2,
        "maxAccess": 3,
        "constraints": {
          "ranges": [
            { min : 4, max 9 },
            { min : 11 },
          ]
        },
        "defVal": 5
      }
```

or a scalar with octet string size constraints:
```
 {
    name: "sysDescr",
    type: snmp.MibProviderType.Scalar,
    oid: "1.3.6.1.2.1.1.1",
    scalarType: snmp.ObjectType.OctetString,
    maxAccess: snmp.MaxAccess['read-write'],
    constraints: {
        sizes: [
            { min: 1, max: 3 },
            { min: 5 }
        ]
    }
}
```

**Comment by derrell** [comment]
The implication, of course, is that a SET operation that is outside of the allowed ranges will return an error rather than allowing the SET to succeed.

**Comment by markabrahams** [comment]
This is great @derrell!  I had the exact same thinking to leave the "constraints" object in a scalar provider / table column provider object flexible enough to add size, range, etc. constraints even though I hadn't gotten to implementing them initially.  This fulfils that vision! :-)

**Comment by markabrahams** [comment]
So @derrell - if RowStatus and persistence are settling down, onto this one next then?!? :-)

**Comment by derrell** [comment]
SGTM! I have to say, I've really enjoyed collaborating with you on all of these recent changes. You are the exemplar of how to motivate contributors while also retaining the style and architecture you feel is important in your own project. You're open to changes and your communication style is friendly and very clear. It's been a pleasure. Just thought you should know!

**Comment by markabrahams** [comment]
Thanks for the kind words @derrell!  The project doesn't get a huge number of code contributors, so I too have enjoyed collaborating with you on these changes - it's a rare treat!  It's also nice seeing the agent's set of features and usefulness steadily improve after a fairly basic beginning about a year ago :-)

**Comment by markabrahams** [comment]
Just merged #161, so this should be good to go now!

**Comment by derrell** [comment]
Cool!

**Comment by markabrahams** [comment]
I've implemented the MIB parsing of ranges and sizes, and added reading these into the providers in `ModuleStore.getProvidersForModule()`.  If I haven't messed anything up, this should complete the ranges and sizes sub-types functionality end-to-end (except a little bit of README documentation!)

Pushed to master now and published in version 3.3.1 of the npm.

**Comment by markabrahams** [comment]
Superb!  I think this can be considered as completed now?

**Comment by derrell** [comment]
I should be back at the point that I can test with my app by later today. I'll remove my manual constraint addition and ensure that the constraints in the MIB file are honored. Having completed that, I'll close out this issue. Thanks.

**Comment by derrell** [comment]
Looks good in my testing, so far! Closing. Thanks.
