### ISSUE TITLE
ResponseInvalidError: Failed to decrypt PDU

### ISSUE THREAD

**Issue by crxtech** [markabrahams/node-net-snmp#172]
I'm trying to do a get with SNMPV3 with sha/aes on a few Cisco nexus 2348's, The frustrating thing is it works about 30% of the time, the rest of the time I get the error:
`ResponseInvalidError: Failed to decrypt PDU: TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined`

When I run the command via ternminal it works everytime.
`sudo snmpget -v3 -l authPriv -u userName -a sha -A 'theauthkey' -x AES -X 'theyencryptkey' 127.0.0.1 1.3.6.1.2.1.1.1.0`

I've also used wireshark to monitor the SNMP get responses, and even when I get the above error, I still see the valid response in wireshark. I see no difference between a successful response and one with the above error in wireshark.

Unfortunately I'm behind a firewall and cannot post code without completely retyping it, but here is most of it:

```
var snmp = require("net-snmp");

const options = {
  port: 161,
  timeout: 9000,
  disableAuthorization: false
};

const user = {
  name: "example-trap",
  level: snmp.SecurityLevel.authPriv,
  authProtocol: snmp.AuthProtocols.sha,
  authKey: "theauthkey",
  privProtocol: snmp.PrivProtocols.aes,
  privKey: "theyencryptkey",
};

let session = snmp.createV3Session(127.0.0.1, user, options);

session.get(["1.3.6.1.2.1.1.1.0"], function(error, varbinds) {
 //code to handle errors and response.
});
```

**Comment by crxtech** [comment]
Line 1496 of index.js readPdu(decryptedPduReader, true) is throwing the error. The original error is:[invalidAns1Error]: encoding too long.
The comments above the catch mention really really occasional truncation, but this seems like the opposite of that, and the catch can't handle it, and return the error ResponseInvalidError: Failed to decrypt PDU. I have noticed an occasion _size of 140, but its 141 most of the time, and I have recieved the error for both sizes.

logging the value of   decryptedPduReader to the console, shows the same data regardless if the error is thrown or not. There doesn't seem to be any pattern to the error. It could work 5 times, then error the next 10.

I've tried to reproduce this with my synology nas at home, but can't reproduce the error outside of work...

**Comment by crxtech** [comment]
I've figured out the issue... I didn't realize the cisco router was configured with aes256! (I don't have access to the configs) That's why it only worked sometimes, when the bits happened to all be under 129.

I saw your recent post (bug 154) about cisco using non standard aes256 and how its a bad idea. Unfortunately I don't have a say in the matter. I will try, but I doubt they will be willing to use 128.

I tried aes256b and aes256r from your documentation and they both time out. I haven't had a chance to trouble shoot them yet, but should have time later today. Has anyone successfully used this package with aes256 to your knowledge? 

Will report back if I get them working. Thanks

**Comment by markabrahams** [comment]
Hi @crxtech - I've used AES256 with Reeder and Blumenthal key localization against the Net-SNMP agent successfully.  I haven't heard reports from anyone else to date.

**Comment by crxtech** [comment]
After further review the routers are using aes128. I tracked the error to ans1-ber/reader.js, function readLegth, line 100:
```		if (lenB > 4)
			throw InvalidAsn1Error('encoding too long');```

Commenting out the if statement that throws the error seems to stop the issue for me and everything still seems to work as it should. Will this break anything else?

I don't fully understand how the offset works, but every time offset gets to 78, if lenB >132 it fails. Once offset gets to 78 lenB gets read as a random hex value from our response.

**Comment by markabrahams** [comment]
Hi @crxtech - if you can test scenarios with the same device with v2c and with v3 but without authentication and encryption (noAuthNoPriv), that would be useful to narrow this down to just an encryption issue, not some other part of the decoding.

Also, if you can supply packet captures for the failing scenarios, that would be helpful.  If this is only reproducible with v3 authPriv, then can you create a temporary v3 authPriv user on the device, generate the packet capture, and share the credentials, which would allow me to simulate the decrypt as well.

Also, can you send the full stack trace for the error?

As to your question, commenting out the `lenB > 4` might not catch other invalid response scenarios - meaning these scenarios might just break in another place.  Also, that check is perhaps catching too much, and the proper solution may be to refine it.

**Comment by gavinaiken** [comment]
I have some Cisco NXOS devices using SNMPv3 / AES128 also throwing this exact same error. I haven't had a chance yet to dig into it with packet captures etc. Will be aiming to do that within a week or so. Here's the stack trace I see:

```
ResponseInvalidError: Failed to decrypt PDU: TypeError [ERR_INVALID_ARG_TYPE]: The \"data\" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at Message.decryptPdu (/usr/local/collector/4305/collector/collector-server/node_modules/net-snmp/index.js:1384:16)
    at Message.processIncomingSecurity (/usr/local/collector/4305/collector/collector-server/node_modules/net-snmp/index.js:1344:15)
    at Session.onMsg (/usr/local/collector/4305/collector/collector-server/node_modules/net-snmp/index.js:2033:17)
    at Socket.emit (events.js:315:20)
    at UDP.onMessage (dgram.js:910:8)
```

**Comment by crxtech** [comment]
> Hi @crxtech - if you can test scenarios with the same device with v2c and with v3 but without authentication and encryption (noAuthNoPriv), that would be useful to narrow this down to just an encryption issue, not some other part of the decoding.
> 
> Also, if you can supply packet captures for the failing scenarios, that would be helpful. If this is only reproducible with v3 authPriv, then can you create a temporary v3 authPriv user on the device, generate the packet capture, and share the credentials, which would allow me to simulate the decrypt as well.
> 
> Also, can you send the full stack trace for the error?
> 
> As to your question, commenting out the `lenB > 4` might not catch other invalid response scenarios - meaning these scenarios might just break in another place. Also, that check is perhaps catching too much, and the proper solution may be to refine it.

First, thank you for taking the time too look at my issue. Unfortunately I work behind a firewall and have no access to the internet, which makes it very challenging to give you enough info for a possible bug. I can talk to the hardware owners to see if they would be willing to create a v2c account for me to do some testing with to narrow this down to just an encryption issue and report back.

**Comment by crxtech** [comment]
Hi @markabrahams. I know its been awhile, but I was able to do alot more testing and it seems to be an issue with the Nexus AES128. If I use authNoPriv it works every time. The only way to duplicate the error is with authPriv with AES.

As a temporary fix I have lines 97-101 of  ans1-ber/reader.js comment out and that seems to fix the issue, however I have no idea what side effects this might have.
```
if ((lenB & 0x80) == 0x80) {
		lenB &= 0x7f;

		// if (lenB == 0)
			// throw InvalidAsn1Error('Indefinite length not supported');

		// if (lenB > 4)
			// throw InvalidAsn1Error('encoding too long');

		if (this._size - offset < lenB)
			return null;

		this._len = 0;
		for (var i = 0; i < lenB; i++)
			this._len = (this._len << 8) + (this._buf[offset++] & 0xff);

	} else {
		// Wasn't a variable length
		this._len = lenB;
	}
```

**Comment by markabrahams** [comment]
Thanks @crxtech and @gavinaiken for the additional info.  If either of you (or anyone else!) is able to post a packet capture of a failed AES128 authPriv GetRequest to a Nexus, that would go a long way towards helping me resolve this.

**Comment by gavinaiken** [comment]
Yep, still planning on doing that when possible. We have a few devices which do this regularly but all of them are in remote locations where we don't have direct access to the box running the snmp polling, so it's very difficult to get the capture. Hoping a more accessible device will start doing it to make the task a lot easier!

**Comment by markabrahams** [comment]
@crxtech - I've disabled the "encoding too long" check in the `asn1-ber` `readLength()` function, which is what fixed your problem.  Even though it's a pretty unusual encoding, it seems to be valid in your case, and it seems a good approach to allow longer, less common encodings if they're indeed valid.
