### ISSUE TITLE
Feature request: add capability to submit binary octet string as array or buffer or ???

### ISSUE THREAD

**Issue by derrell** [markabrahams/node-net-snmp#175]
As an example of the need for this capability, from IPV6-TC:

```
Ipv6Address ::= TEXTUAL-CONVENTION
     DISPLAY-HINT "2x:"
     STATUS       current
     DESCRIPTION
       "This data type is used to model IPv6 addresses.
        This is a binary string of 16 octets in network
        byte-order."
     SYNTAX       OCTET STRING (SIZE (16))
```

So an Ipv6Address is an octet string of length 16. The textual representation of an IPv6 address is 32 characters (when excluding the colons), e.g., "fdf1e8b1beef000000000000000001234". When passing this string in as, for example, as a table column value in the row array of a table that includes Ipv6Address -- especialy one in which the Ipv6Address is an index column -- each character is converted individually as part of the OID (in `getOidAddressFromValue`) using `c.charCodeAt()`, yielding a 32-byte result instead of 16 bytes.

In order to get around this, the best I've found so far is to convert the address to a binary string using a function like the following:

```
function hexToIpv6(s)
{
  // Get an array of strings by splitting at every 2 characters, and
  // then parse each pair of hex characters into an integer. Finally
  // combine those 8-bit numbers back into a string, assuming each
  // 8-bit number is the byte value
  return String.fromCharCode.apply(
    null,
    s.match(/.{2}/g).map(v => parseInt(v, 16)));
}
```

Passing a Buffer or Array containing the 16 components of the address seemed appropriate, but crashes (`charCodeAt` is still called, but doesn't work on Arrays or Buffers).

If there isn't a better way to work with octet strings that must contain binary data, this issue requests that such a capability be added.

**Comment by derrell** [comment]
This problem may exist only when the octet string is used in an index. It seems that passing in a Buffer in other cases may work as expected.

Here's a specific use case, from IPV6-MIB, where an Ipv6Address is part of the index:

```
 ipv6RouteTable OBJECT-TYPE
     SYNTAX     SEQUENCE OF Ipv6RouteEntry
     MAX-ACCESS not-accessible
     STATUS     current
     DESCRIPTION
       "IPv6 Routing table. This table contains
       an entry for each valid IPv6 unicast route
       that can be used for packet forwarding
       determination."
     ::= { ipv6MIBObjects 11 }

 ipv6RouteEntry OBJECT-TYPE
     SYNTAX     Ipv6RouteEntry
     MAX-ACCESS not-accessible
     STATUS     current
     DESCRIPTION
             "A routing entry."
     INDEX   { ipv6RouteDest,
               ipv6RoutePfxLength,
               ipv6RouteIndex }
     ::= { ipv6RouteTable 1 }

 Ipv6RouteEntry ::= SEQUENCE {
         ipv6RouteDest           Ipv6Address,
         ipv6RoutePfxLength      INTEGER,
         ipv6RouteIndex          Unsigned32,
         ipv6RouteIfIndex        Ipv6IfIndexOrZero,
         ipv6RouteNextHop        Ipv6Address,
         ipv6RouteType           INTEGER,
         ipv6RouteProtocol       INTEGER,
         ipv6RoutePolicy         Integer32,
         ipv6RouteAge            Unsigned32,
         ipv6RouteNextHopRDI     Unsigned32,
         ipv6RouteMetric         Unsigned32,
         ipv6RouteWeight         Unsigned32,
         ipv6RouteInfo           RowPointer,
         ipv6RouteValid          TruthValue
     }

 ipv6RouteDest OBJECT-TYPE
     SYNTAX     Ipv6Address
     MAX-ACCESS not-accessible
     STATUS     current
     DESCRIPTION
       "The destination IPv6 address of this route.
       This object may not take a Multicast address
       value."
     ::= { ipv6RouteEntry 1 }
```

**Comment by markabrahams** [comment]
Hi @derrell - I haven't tested this at all, but if it's just an OID index mapping issue, then the OctetString case in `Mib.prototype.getOidAddressFromValue` could detect a buffer value and act accordingly e.g.

```
case ObjectType.OctetString:
    if ( value instanceof Buffer ) {
        // Buffer
        oidComponents = Array.prototype.slice.call (value);
    } else {
        // string
        oidComponents = [...value].map (c => c.charCodeAt());
    }
    break;
```

**Comment by markabrahams** [comment]
PR #176 is merged, which fixes this issue.
