### ISSUE TITLE
[question] - How to correctly parse Counter64 type?

### ISSUE THREAD

**Issue by jamacku** [markabrahams/node-net-snmp#178]
Hi,
I'm trying to get 64bit Counter `IF-MIB::ifHCOutOctets` and store it to db.

When I log return value I get something like this: 

```
console.log(result);
> [ <Buffer 58 f0>, <Buffer 01 70 5a bd> ]
```

I assumed that it's upper and lower 4 bytes, hence I'm tried to parse it via `readBigInt64BE` like this:

```
const buff1 = serverLogs.if_in_traffic64[0];
const buff2 = serverLogs.if_in_traffic64[1];

let buff = Buffer.alloc(8);
const a = Buffer.concat([buff1, buff2]);

buff.fill(a, 8 - Buffer.byteLength(a));

console.log(buff);
console.log(buff.readBigInt64BE(0).toString());
console.log(+buff.readBigInt64BE(0).toString());
```

But results are way off from reality. I realized that when I took only lower portion it's correct since it matches 32bit counter `IF-MIB::ifOutOctets`.

May I ask you how to put together this array of buffers so I could utilize full 64bit of counter?

Thank you.

**Comment by jamacku** [comment]
Ohh, newer mind I'm just overworked. I realized that first element of array is loopback IF.

Btw love the library and sorry for spam.

**Comment by markabrahams** [comment]
No problems @jamacku! Thanks for the kind word for the project, and thanks for rounding this one off!
