### ISSUE TITLE
SNMP Agent tablerow from external source

### ISSUE THREAD

**Issue by ernestclyde** [markabrahams/node-net-snmp#185]
Hello, 
currently i am experimenting to pull data from external source (redis) and it seems that the handler from mib.registerProvider will only run if there's a mib.addTableRow.

is it possible to serve snmp data without mib.addTableRow?

**Comment by markabrahams** [comment]
Hi @ernestclyde - from RFC 3411, "An Architecture for Describing Simple Network Management Protocol (SNMP) Management Frameworks", Section 2.10:

> Management information is viewed as a collection of managed objects,
> residing in a virtual information store, termed the Management Information
> Base (MIB)

So all data served via SNMP must reside in the MIB - either in a table row or in a scalar value.

**Comment by ernestclyde** [comment]
I see, i was planning to store the values on redis and create multiple SNMP agent that will serve the same data behind a load balancer

**Comment by markabrahams** [comment]
If you want to serve SNMP data from redis, then you'd need to implement the MIB semantics in redis.  If it was using this library, you'd have to write an alternative `Mib` module implementation that stored data in redis, and provided the interface to the agent for OID lookups, MIB tree traversal, etc.
