### ISSUE TITLE
InvalidAsn1Error: Expected 0x2: got 0x81

### ISSUE THREAD

**Issue by wdmlsx** [markabrahams/node-net-snmp#187]
This exception causes the program to be pushed out.

**Comment by markabrahams** [comment]
Hi @wdmlsx - if you could read and follow the guidelines in CONTRIBUTING.md on what to include in a bug report - that would be great. In particular these points:

- Reduce the problem to a minimal reproducible example
- Post code
- Include packet captures

**Comment by markabrahams** [comment]
This library no longer makes use of the `asn1-ber` `readInt()` type tag check, so this error is not produced any more.
