### ISSUE TITLE
Handling of sign for four bytes integers

### ISSUE THREAD

**Issue by IvanVegaR** [markabrahams/node-net-snmp#193]
Hi,

I've been playing around with the package, which proved to be quite a useful package :).

I was experiencing some unexpected behaviour when snmpgetting negative integer values which are encoded using all 4 bytes, e.g. -2147483648 (0x80000000). The value I've got back at the varbind is 2147483647 ((0x7fffffff). After some code inspection I found that in _'function readUint (buffer, isSigned) {_' the sign is applied using the shift operator. Which, I think, might be problematic  for shifts beyond 31.

When getting the very same OID using Linux snmpget utility resolves in the expected value, so I think that the ASN1 data received from the Agent is well formatted.

**Package version:** 3.5.6
**NodeJS version:** v14.16.0
**Contents of the buffer when invoking readUint:** <Buffer 02 04 80 00 00 00>
The SNMP Type, is properly set to 2 (ObjectType.Integer), so _readUint_ is invoked via _readInt_.

Kind regards
 Ivan

**Comment by markabrahams** [comment]
Thanks for reporting this @IvanVegaR.  Yes you're right - 32 bits shifts weren't working.  I've fixed this in master now and published the fix in version 3.5.8 of the npm.

**Comment by IvanVegaR** [comment]
Hi,

Thanks for the quick fix. It's working nice and smooth.

Kind regards
 Ivan

**Comment by markabrahams** [comment]
No problems @IvanVegaR - thanks for confirming the fix!
