### ISSUE TITLE
How to wait for multiple results

### ISSUE THREAD

**Issue by mwoodpatrick** [markabrahams/node-net-snmp#195]
I need to write a node app that collects data from multiple nodes using snmp then when all data is gathered to process all the results and then generate a report. Is there a recommended way to do that. It seems I could promisify the get & walk functions and then call "Promise.al"l to wait for all the promises to be finalized and then do my custom processing. Is this the best approach or is there a better one?

**Comment by markabrahams** [comment]
Hi @mwoodpatrick - yes, promisify and Promise.all is the best approach I can think of for your scenario.

**Comment by gavinaiken** [comment]
Another possibility is to use the excellent async npm library to run all your functions which use a callback and then do something when they have all completed. You could use `each` to run them in parallel https://caolan.github.io/async/v3/docs.html#each or `eachSeries` if you want to collect data from one node at a time.
