### ISSUE TITLE
User level copied from user name

### ISSUE THREAD

**Issue by thejhh** [markabrahams/node-net-snmp#210]
I noticed that level is copied as the user name. Isn't this a bug?

https://github.com/markabrahams/node-net-snmp/blob/bc0d88881f4159cde81970c8a9b96fe5392072e8/index.js#L1569

**Comment by markabrahams** [comment]
Hi @thejhh - yes that's definitely a bug - thanks for reporting!  I've fixed this in master now and in version 3.8.3 of the npm.
