### ISSUE TITLE
Update MIB tree from existing MIB file

### ISSUE THREAD

**Issue by eladGishri** [markabrahams/node-net-snmp#234]
I'm implementing an SNMP agent. 
I using my company's existing MIB file.

I got and registered the providers but as stated in the documentation it doesn't update the MIB tree.
Is there a way to update the entire MIB tree of an enterprise size MIB file?

**This is my current code:**
```
let store = snmp?.createModuleStore();
store.loadFromFile(mibPath);
let jsonModule = store?.getModule(<ModuleName>);

// Fetch MIB providers, create an agent, and register the providers with your agent
const providers = store.getProvidersForModule(<ModuleName>);
let mib = agent.getMib();
mib.registerProviders(providers);
```

**Comment by markabrahams** [comment]
Hi @eladGishri - yes, you can find the calls you need to populate your MIB in the README documentation:
- for scalars: `mib.setScalarValue (scalarProviderName, value)` - call once for each scalar provider
- for tables: `mib.addTableRow (tableProviderName, row)` - call as many times as you like for each table provider
