### ISSUE TITLE
RequestInvalidError: Unknown type '[object Object]' in request

### ISSUE THREAD

**Issue by morrisrob** [markabrahams/node-net-snmp#244]
Hello, I am receiving a "RequestInvalidError: Unknown type '[object Object]' in request" error and I have confirmed that this issue was introduced in v3.9.6.  I am not able to reproduce this same error in v3.9.5.  

Here is an example of the `varbinds` getting passed into the `writeVarbinds` function; it seems that the issue is that there is an object in the `type` property and not the expected integer value associated with the `ObjectType` enum. 
![image](https://github.com/markabrahams/node-net-snmp/assets/51250711/3b211edd-b1ee-4889-8f6a-5ea520098152)

I am only seeing this issue in tables and specifically with entries with the `DisplayString` Syntax.  Here is the MIB entry associated with this:
![image](https://github.com/markabrahams/node-net-snmp/assets/51250711/b736c2d7-ab98-4e35-b45b-9f9f7ae1720a)

**Comment by markabrahams** [comment]
Hi @morrisrob - thanks for reporting this.  I've pushed a fix for this and published it in version 3.10.1 of the npm.

**Comment by morrisrob** [comment]
@markabrahams, thank you for the very quick response and fix! I have confirmed that this issue is resolved in 3.10.1.  Thanks!
