### ISSUE TITLE
Runtime error during parsing in bundled apps

### ISSUE THREAD

**Issue by CarlHenrik** [markabrahams/node-net-snmp#258]
### Issue
Assigning value to property 'length' for an object holding a string:
https://github.com/markabrahams/node-net-snmp/blob/0698c0eb3c85d6a5dbdb680efa8f313b6d459ad8/lib/mib.js#L44-L59

This code produces no error when running this lib "as is", since `this.builder` is just a generic mutable object. However, certain bundlers, such as Rollup, performs code optimizations so that the object `this.builder` becomes an imutable string primitive type with readonly property `.length`. This causes runtime error on the following line:
https://github.com/markabrahams/node-net-snmp/blob/0698c0eb3c85d6a5dbdb680efa8f313b6d459ad8/lib/mib.js#L51

> Cannot assign to read only property 'length' of string ''

One can argue that this is not really an issue with the library itself, but the assignment `this.builder.length = 0;` is unnecessary as the line above it assigns the object an empty string: `this.builder = "";`. The length is already 0 at line 51.

### Proposed solution
Omit line 51 altogether, as it serves no purpose and breaks the lib's compatibility with bundlers/code optimizers.
https://github.com/markabrahams/node-net-snmp/blob/0698c0eb3c85d6a5dbdb680efa8f313b6d459ad8/lib/mib.js#L51

**Comment by markabrahams** [comment]
Hi @CarlHenrik - thanks for reporting that.  I've implemented your proposed solution now and published this in version 3.15.1 of the npm.
