### ISSUE TITLE
Send Trap and Create Agent on Same Port

### ISSUE THREAD

**Issue by michaelnem** [markabrahams/node-net-snmp#262]
Is it possible to send a trap from a session and create an SNMP (2c) agent on the same port using the `node-net-snmp` package?

Use Case:
I need to send a trap message where the source port is also the port used to query the agent. This requires both sending traps and listening as an agent on the same port.

Let me know if this is feasible or if there's a workaround.

**Comment by markabrahams** [comment]
Hi @michaelnem - in that scenario, the `agent` is bound to the UDP port.  Sending a trap requires a source UDP port bind to a `session`.  A typical OS will not allow the second entity (the session) to bind to the same UDP port as the first (the agent), so this won't inherently work.

A workaround would be to use a different source port and then use NAT to rewrite the source port after generation.  Although I couldn't recommend that approach!

**Comment by markabrahams** [comment]
I hadn't considered the proxy idea - this is better than the NAT that I suggested for your use case.

On your request to allow an agent's socket to send traps: What this design means is that you're using the same socket for a client and server function.  This introduces the need to multiplex/demultiplex on both ends of the traffic flow.  It's an additional layer that introduces complexity and risk that isn't otherwise there and doesn't solve any problem that I can conceive.  I'd make the same argument against mixing server/client functionality into one socket in the design of any service - not just this one related to SNMP.  As such, I wouldn't recommend the design, nor add the capability to the library.  With that being said, you're obviously using this design for a reason, so feel free to elaborate on what that is and present your case to support this - there's a chance I can be persuaded given a good argument! :-)

**Comment by mikila85** [comment]
@markabrahams +1 we also use this functionality and already implemented a proxy for it. our printer is auto detected and sending traps on 161 as source port, the server is intended to reach back to the printer on the same port (161) but it is already in use by the agent - hence the proxy. we would love to eliminate the proxy overhead and be able to listen on the same port the trap sends from.

**Comment by michaelnem** [comment]
Thanks for your help previously. I managed to monkey-patch a workaround to send traps from the same port as the agent. Here's a brief snippet:

```js
const originalCreateAgent = snmp.createAgent;
const originalSend = snmp.Session.prototype.send;

const agentSockets = {};
snmp.createAgent = function(opts, cb, mib) {
  const agent = originalCreateAgent.call(this, opts, cb, mib);
  for (const key in agent.listener.sockets) {
    const port = parseInt(key.split(':')[2], 10);
    agentSockets[port] = agent.listener.sockets[key];
  }
  return agent;
};

snmp.Session.prototype.send = function(req, noWait) {
  if (this.sourcePort && agentSockets[this.sourcePort] && this.transport === "udp4") {
    const socket = agentSockets[this.sourcePort];
    const buffer = req.message.toBuffer();
    socket.send(buffer, 0, buffer.length, req.port, this.target, (error) => {
      if (error) req.responseCb(error);
      else noWait ? req.responseCb(null) : this.registerRequest(req);
    });
    return this;
  }
  return originalSend.call(this, req, noWait);
};
```
It's not ideal, but it works for now. Hopefully this helps anyone facing similar issues!

**Comment by mikila85** [comment]
Thank you very much, tested and it is working. I just wish it was a part of the library it self.

**Comment by markabrahams** [comment]
@mikila85 - if I've understood your description correctly - and I'm not sure that I have even after five reads! - you're reusing the source port number of the printer's incoming trap - attempting to assign this as the source port number of the server's subsequent poll (the server acting as an RFC 3413 "Command generator").  I'd recommend against this - these are two different interactions and shouldn't be coupled, as you're assuming that a particular source port selected on one device is also available for selection on a separate device; this is not guaranteed to be a correct assumption, as you've discovered.  Each device should - and typically does by default - make its own source port selection independently.

As mentioned previously, I'm open to considering this as a library feature, but I can't yet see a scenario that would justify the additional risk and complexity of supporting such a design.  While this remains the case, I won't be adding it to the library.
