### ISSUE TITLE
Cannot load mibs using a path that contains periods

### ISSUE THREAD

**Issue by ChrisFigura** [markabrahams/node-net-snmp#263]
Hi,

I'm seeing an issue when I try to load mibs into a module store using a path that contains periods.

Example:
```js
const store = snmp.createModuleStore();
store.loadFromFile('C:\\Source\\service-1.0.0\\mibs\\example.mib');
```

When I load mibs with a path like this, my program crashes and this error is logged repeatedly:

```
Unable to mount node '...', cannot resolve parent object '...'.
```

This seems to happen because of [line 130 in lib/mib.js](https://github.com/markabrahams/node-net-snmp/blob/b077c9de9195dc5330d1aa63bf9e72193ca32604/lib/mib.js#L130C1-L130C135), where the name of the file being processed is extracted using `FileName.split('/')[FileName.split('/').length - 1].split('.')[0]`.

Could you please update this so paths that contain a period are supported? I've made a PR with a fix that works for my environment.

Thank you!

**Comment by markabrahams** [comment]
Thanks @ChrisFigura for this!  I've merged into master now and published in version 3.16.1 of the npm.
