### ISSUE TITLE
Support for AgentX

### ISSUE THREAD

**Issue by maxmeyer** [markabrahams/node-net-snmp#4]
Does your library support [AgentX](https://www.ietf.org/rfc/rfc2741.txt) to register itself to a Master SNMP agent?

**Comment by stephenwvickers** [comment]
Unfortunately net-snmp does not provide any agent support, and I also don't think AgentX would be much if it did in this case.

**Comment by markabrahams** [comment]
I have interest in a Node implementation of AgentX - I see this as arguably more useful than SNMP agent support itself.  Re-opening.

**Comment by markabrahams** [comment]
@maxmeyer - I've implemented AgentX subagent support in the library now, and published this in v2.6.0 of the npm.

Usage documentation is in the README.md.

**Comment by maxmeyer** [comment]
Thanks.
