### ISSUE TITLE
Specifying Context name for snmp V3

### ISSUE THREAD

**Issue by KRKroening** [markabrahams/node-net-snmp#56]
I am trying out the new release to see if it will work for my use case. One issue I am encountering is the ability to specify the context name in the requests. As is, my requests all return NoSuchObject. I have been working with the net-snmp cmd line tools to communicate with my device so far, so I know the oid and credentials are correct. I am able to replicate the NoSuchObject error via cmd if I remove the context option (` -n <context> `) [net-snmp docs](http://www.net-snmp.org/wiki/index.php/TUT:SNMPv3_Options)  

I've looked through the documentation and source code. In the code, I've found reference to contextName in terms of parsing the pdu, but haven't been able to discern a way of specifying the context.

Is there any examples or additional documentation I could be pointed to that would clear this up for me? Is it possible to set the context in this way?

Thank you

**Comment by markabrahams** [comment]
Hi @KRKroening - at the moment, I haven't supplied an option to specify the context.  This should be relatively straightforward to add.  I'll have a look at this over the next day or so.

**Comment by markabrahams** [comment]
@KRKroening - I've just added this now.  There's a new "context" field added to the "options" object that you pass to the snmp.createV3Session() call, so SNMPv3 contexts should work OK now.  Published to npm in net-snmp v2.1.2.

Example usage:
`var session = snmp.createV3Session (<address>, <user-object>, {context: "mycontext"});`

**Comment by KRKroening** [comment]
@markabrahams Thank you very much. Tested your newest changes this morning and it worked perfectly.
