### ISSUE TITLE
AES 128 option for privacy protocol

### ISSUE THREAD

**Issue by gavinaiken** [markabrahams/node-net-snmp#57]
Hi Mark, congrats on taking over support for the repo (and thanks to Stephen for all the original work and years of support for it)! We've been using the v2c functionality of the library for a few years and it has been great.

Really excited to see support for v3, and traps / inform receivers, will probably be using both features quite soon. 

Question - do you have any plans to support AES 128 bit encryption as specified in RFC 3826 https://tools.ietf.org/html/rfc3826 ?

thanks!

**Comment by markabrahams** [comment]
Hi @gavinaiken - thanks!  Yep - I've also been a long-time user of the v2c capability of node-net-snmp and as such am very grateful for the work Stephen put into this.

Yes, I would like to get AES-128 support implemented.  Compared to the DES padding inconsistencies I've had to deal with, should be a walk in the park :-)  Just finishing off SNMP agent support over the next few days, and should be able to have a look at AES-128 within the next week or so.

**Comment by gavinaiken** [comment]
Fantastic, thanks!

**Comment by markabrahams** [comment]
Hi @gavinaiken  - I've just released AES-128 support in v2.5.0 of the npm.

Just adds `snmp.PrivProtocols.aes` as an option for `user.privProtocols` to use.

**Comment by gavinaiken** [comment]
You're a hero :)

**Comment by markabrahams** [comment]
Heh - thanks - hopefully it works ok for you! :-)

**Comment by gavinaiken** [comment]
Will be aiming to test SNMPv3 with AES out quite thoroughly towards the end of next week, on a variety of devices, can let you know how it goes if you are interested.

**Comment by markabrahams** [comment]
Yes thanks - if you could post back here on how you get on, it would definitely be good to widen the test pool, as mine was fairly limited.

**Comment by gavinaiken** [comment]
Sorry, haven't got a chance to test this yet, looking like it will be around a week or so before I clear my backlog sufficiently to do so. Will report back as soon as I have a chance.

**Comment by markabrahams** [comment]
No problems - I've been testing AES-128 sporadically in a few scenarios, and so far so good.

**Comment by unchained-za** [comment]
I used it in a one device type simulation environment to simulate a real-world issue and it worked perfectly there.

**Comment by gavinaiken** [comment]
Finally managed to spend some time testing v3. AES encryption seems to be working fine, but I am having some trouble getting data from some Cisco devices, as per this issue: https://github.com/markabrahams/node-net-snmp/issues/64#issuecomment-605492794

**Comment by markabrahams** [comment]
Great thanks @gavinaiken - I'll close this as completed and we'll take up the specific issue with the Cisco devices in #64.
