### ISSUE TITLE
subtree no returns

### ISSUE THREAD

**Issue by sabasespin** [markabrahams/node-net-snmp#60]
The feedCb function is in an indefinite cycle

I am trying to get an array of the oid returned in the function and it does not finish executing even when there are no more children to read

**Comment by markabrahams** [comment]
Hi @sabasespin - I've just updated the CONTRIBUTING.md file with some guidelines on submitting bug reports.  Can you have a read of the "Bug Reports" section, and in particular I'm after a minimal reproduction of the problem (point 4), and also packet captures for both the non-working example with this library and a working example using another tool like the NetSNMP command line (point 5).  Thanks!

**Comment by markabrahams** [comment]
This issue has all the momentum of an immovable object that has *already* been stopped by an unstoppable force.

**Comment by markabrahams** [comment]
Yes, indeed - thanks @christopher-nielsen-ny !  And if so, this is fixed in version 3.9.8 of the npm.
