### ISSUE TITLE
SNMP Agent walk identifier is too short

### ISSUE THREAD

**Issue by ernestclyde** [markabrahams/node-net-snmp#62]
Hello

currently i installed net-snmp 2.5.2 and copied snmp agent from examples,
works great except that when i try to do a snmp walk with no oid start option the agent crash with an error of:
/usr/lib/node_modules/net-snmp/index.js:3679
throw new RangeError('object identifier is too short')

also find out that snmpwalk works when oid start is 1.3.6

**Comment by markabrahams** [comment]
Hi @ernestclyde - thanks for reporting this.

I've fixed in this in now - published fix is in npm version 2.5.4.

**Comment by ernestclyde** [comment]
Hello
i also noticed the same on get request

**Comment by markabrahams** [comment]
Hi @ernestclyde - this is fixed now - published fix is in version 2.6.5 of the npm.
