### ISSUE TITLE
SNMPV3: ResponseInvalidError: Unexpected Report PDU

### ISSUE THREAD

**Issue by dattatelite** [markabrahams/node-net-snmp#64]
SNMPV3 seems to work only with noAuthNoPriv.

Both authNoPriv and authPriv throw the same error: 
### "ResponseInvalidError: Unexpected Report PDU"

# My code:
var options = {
      port: 161,
      retries: 1,
      timeout: 5000,
      transport: "udp4",
      trapPort: 162,
      version: snmp.Version3,
      idBitsSize: 32,
      context: ""
    };
    //working
    var user1 = {
      name: "blinkybillno",
      level: snmp.SecurityLevel.noAuthNoPriv,
    };
    var user2 = {
      name: "blinkybilltry",
      level: snmp.SecurityLevel.authNoPriv,
      authProtocol: snmp.AuthProtocols.md5,
      authKey: "somethingisetterthannothing"
    };
    var user3 = {
      name: "blinkybill",
      level: snmp.SecurityLevel.authPriv,
      authProtocol: snmp.AuthProtocols.sha,
      authKey: "123456789012345abc",
      privProtocol: snmp.PrivProtocols.des,
      privKey: "123456789012345abc"
    };
    let connectionStatus;
    let session = await snmp.createV3Session (ipAddress, user3, options);
    //let oids = ["1.3.6.1.2.1.1.3.0"]; //sysUpTime
    let oids = ["1.3.6.1.2.1.1.1.0"]; //sysDescr
    let data
    var promiseGetOid = new Promise(async function(resolve, reject){
    await session.get (oids, async function (error, varbinds) {
      if (error) {
          console.error (error);
          reject(error);
      } else {
              if (snmp.isVarbindError (varbinds[0])){
                  console.error (snmp.varbindError (varbinds[0]))
                  reject(snmp.varbindError (varbinds[0]));
              }
              else{
                  data = await varbinds[0].value.toString();
                  resolve (data);    
              }
      }
    });
    });

**Comment by unchained-za** [comment]
I've been using it successfully with authPriv, that's what I tested with initially. I didn't bother with the trapPort or the idBitsSize and for privProtocol I used both AES and DES and both MD5 and SHA for authProtocol. I cannot remember if I had a problem where host agents had invalid engineIds, that was another issue that I had to deal with.

**Comment by markabrahams** [comment]
A few things to check:
(1) Double-check security credentials - some SNMP agents send a Report PDU if authentication/privacy fails.
(2) Try removing context: "" from the options - a null-string context may have different meaning to no context.
(3) An agent not storing / reporting a correct engine ID could lead to this condition as well.

**Comment by dattatelite** [comment]
> A few things to check:
> (1) Double-check security credentials - some SNMP agents send a Report PDU if authentication/privacy fails.
> (2) Try removing context: "" from the options - a null-string context may have different meaning to no context.
> (3) An agent not storing / reporting a correct engine ID could lead to this condition as well.

Will try this and keep posted.

**Comment by dattatelite** [comment]
> I've been using it successfully with authPriv, that's what I tested with initially. I didn't bother with the trapPort or the idBitsSize and for privProtocol I used both AES and DES and both MD5 and SHA for authProtocol. I cannot remember if I had a problem where host agents had invalid engineIds, that was another issue that I had to deal with.

If you did, how did to tackle around it. Could you please post your snmpv3connect and snmpv3get code.

**Comment by unchained-za** [comment]
If you did, how did to tackle around it. Could you please post your snmpv3connect and snmpv3get code. 

It's late Sunday evening now, will do it in the morning at the office. 

Disclaimer

The information contained in this communication from the sender is confidential. It is intended solely for use by the recipient and others authorized to receive it. If you are not the recipient, you are hereby notified that any disclosure, copying, distribution or taking action in relation of the contents of this information is strictly prohibited and may be unlawful.

This email has been scanned for viruses and malware, and may have been automatically archived by Mimecast Ltd, an innovator in Software as a Service (SaaS) for business. Providing a safer and more useful place for your human generated data. Specializing in; Security, archiving and compliance. To find out more visit the Mimecast website.

**Comment by unchained-za** [comment]
I allow for many of these variable to be passed as parameters in a JSON object, even the request type. I never even tried to use it with promises. This code has actually been implemented as a microservice to be used by other services after having had too many problems with the C++ implementation. 
One thing to watch out for is invalid engineIds, that has messed me around severely. On one site all the hosts were set to the same invalid engineId and that messed the asynchronous SNMP completely up, although it seemed fine with normal command Net-SNMP commands. It also messed with our first C++ SNMP microservice, I haven't really tested the node one in that environment, but it makes complete sense that it should give problems as the engineId, engineBoots and engineTime are all used to validate a request and may cause confusion if there are more than one request active with the same engineId.

// host
var host = 10.0.0.1

// session user
var user = {};
user.name = "userAuthPriv";
user.level = snmp.SecurityLevel.authPriv;
user.authProtocol = snmp.AuthProtocols.md5;
user.authKey = "snmpAuthKey";
user.privProtocol = snmp.PrivProtocols.aes;
user.privKey = "snmpPrivKey";

// session options
var options = {};
options.port = 161;
options.retries = 2;
options.timeout = 2000;
options.backoff = 2.5;
options.transport = 'udp4'
options.version = snmp.Version3;
options.context = undefined;	// unless there is a valid context, haven't tested that yet.

var oids = ["1.3.6.1.2.1.1.1.0", "1.3.6.1.2.1.1.3.0"], "1.3.6.1.2.1.1.5.0";

session = self._createSession(host, user, options);
session = self._createV3Session(host, user, options);

// Usual call and processing as per the examples
session.get(oids, function(error, varbinds)
{
...
});

**Comment by markabrahams** [comment]
@dattatelite - the library uses callbacks, not promises.  In particular:
await session.get...
doesn't actually await, as session.get doesn't return a promise.

Suggestion: check out the examples in the README or in the test or example directory.  For some ideas:
./test/snmp-test.sh -p

Implement without promises - just callbacks - first.  See where your code/parameters differ from a working example.

**Comment by dattatelite** [comment]
Well @markabrahams as you said await on session.get doesn't make sense. But I just declared a promise to make it synchronous. Anyway I removed all of those. But still face the same error. (Code found below)

@unchained-za I used options similar to what is mentioned on your code, also tried marking context as undefined. 

Anyway what works for me in terms of the snmpget via command line is this:
snmpget -v 3 -u blinkybill -l authPriv -a MD5 -A 123456789012345abc -x DES -X 123456789012345abc 192.x.x 1.3.6.1.2.1.1.1.0

The same info is mentioned onto the code as well. Went through the examples, I've copied the 'snmp-get.js' as is. Yet it throws the same "ResponseInvalidError: Unexpected Report PDU" error.

# My current code:
let snmp = require ("net-snmp");
let ipAddress = "192.168.x.x";
//var options = require("option-parser"); //is this even required?
 var options = {
    port: 161,
    retries: 2,
    timeout: 5000,
    transport: "udp4",
    version: snmp.Version3,
    backoff: 2.5
  };

  var user = {
    name: "blinkybill",
    level: snmp.SecurityLevel.authPriv,
    authProtocol: snmp.AuthProtocols.md5,
    authKey: "123456789012345abc",
    privProtocol: snmp.PrivProtocols.des,
    privKey: "123456789012345abc"
  };

  let session = snmp.createV3Session (ipAddress, user, options);
  let oids = ["1.3.6.1.2.1.1.1.0"]; //sysDescr
  //let oids = options.oids; //this throws "Cannot read property 'length' of undefined" in snmp.get

  session.get (oids, function (error, varbinds) {
    if (error) {
      console.error (error.toString ());
    } else {
      for (var i = 0; i < varbinds.length; i++) {
        if (snmp.isVarbindError (varbinds[i]))
          console.error (snmp.varbindError (varbinds[i]));
        else
          console.log (varbinds[i].oid + "|" + varbinds[i].value);
      }
    }
  });

**Comment by gavinaiken** [comment]
I've got this same issue. I have two Cisco devices, and one of them gives me this error but the other one polls successfully. The same `snmpget` command works for both. Here's the snmget commands, identical apart from the IP address being queried:

```
snmpget -v 3 -u v3testuser -l authPriv -a md5 -A v3authpass -x aes -X v3privpass 172.27.255.1 1.3.6.1.2.1.1.1.0
snmpget -v 3 -u v3testuser -l authPriv -a md5 -A v3authpass -x aes -X v3privpass 172.27.240.15 1.3.6.1.2.1.1.1.0
```

And here's my simple node code:

```
const snmp = require('net-snmp');

// Default options
const options = {
    port: 161,
    retries: 1,
    timeout: 5000,
    transport: 'udp4',
    trapPort: 162,
    version: snmp.Version3,
    idBitsSize: 16,
    // context: '',
};

// const host = '172.27.255.1';
const host = '172.27.240.15';

const user = {
    name: 'v3testuser',
    level: snmp.SecurityLevel.authPriv,
    authProtocol: snmp.AuthProtocols.md5,
    authKey: 'v3authpass',
    privProtocol: snmp.PrivProtocols.aes,
    privKey: 'v3privpass',
};

const session = snmp.createV3Session(host, user, options);
const oids = ['1.3.6.1.2.1.1.1.0']; // sysDescr

session.get(oids, function (error, varbinds) {
    if (error) {
        console.error('Error:', error);
        return;
    }
    for (var i = 0; i < varbinds.length; i++) {
        if (snmp.isVarbindError (varbinds[i])) {
            console.error(snmp.varbindError (varbinds[i]));
        } else {
            console.log(varbinds[i].oid + '|' + varbinds[i].value);
        }
    }
});
```

I've tried it with and without the `context` in the options, and with `idBitsSize` of 16 and 32, and it always works against one device, and always gives me this error on the other one:

```
Error: ResponseInvalidError: Unexpected Report PDU
    at Session.onMsg (/Users/gavin/repos/node-core/tasks/node_modules/net-snmp/index.js:1962:23)
    at Socket.emit (events.js:210:5)
    at UDP.onMessage [as onmessage] (dgram.js:861:8) {
  name: 'ResponseInvalidError',
  message: 'Unexpected Report PDU'
}
```

As per the above, I'm sure the security creds are correct since the `snmpget` commands work. 

@markabrahams you said a possible cause of the problem was:

(3) An agent not storing / reporting a correct engine ID could lead to this condition as well.

how would I investigate that further? Or is there another possible cause of this problem?

**Comment by gavinaiken** [comment]
I'm comparing what the node code sends on the wire vs what the command line tools send, using wireshark. Interestingly wireshark shows the node packet as a "malformed packet" so it looks like the code is doing something wrong as compared with the command line tool. Trying to dig into that further...

### command line:
![Screenshot 2020-03-30 at 12 09 52](https://user-images.githubusercontent.com/932263/77906394-ca612a80-727f-11ea-86ef-8e059c6ca63e.png)

### node:
![Screenshot 2020-03-30 at 12 10 54](https://user-images.githubusercontent.com/932263/77906397-cc2aee00-727f-11ea-9d48-ceb82478b01d.png)

**Comment by gavinaiken** [comment]
After further testing with Wireshark, here's what I'm seeing:

The device where I get the `'Unexpected Report PDU'` error with the test node script usually (but not always) sends 2 `report` packets in response to a query. It does this when I use the command line tools, or a node script. The command line tools seem to handle the extra report packet fine, but node throws the error.

On the Cisco device which I can poll successfully I only see one report packet returned.

I have packet captures of the above if that is any use.

**Comment by gavinaiken** [comment]
Reading the spec in the RFC, it looks like the second report PDU is performing time synchronisation as per: https://github.com/markabrahams/node-net-snmp/blob/master/ref/rfc/v3/rfc3414.txt#L1746

![image](https://user-images.githubusercontent.com/932263/77917067-f4234d00-7291-11ea-9bc2-9fcb28f867e4.png)

I can see in my packet captures that the first report PDU has msgAuthoritativeEngineBoots and msgAuthoritativeEngineTime both set to 0:

![image](https://user-images.githubusercontent.com/932263/77917181-20d76480-7292-11ea-8b6c-c831785cd9ec.png)

and the second one has values there, which seems to conform to the spec?

![image](https://user-images.githubusercontent.com/932263/77917236-3b114280-7292-11ea-8da1-eeba45d99d18.png)

**Comment by unchained-za** [comment]
Check the values between you first report and the get-request, also that the engineId stays the same. The time should not differ much and the boots should stay the same.

**Comment by gavinaiken** [comment]
Engine id is the same on all the packets after the initial discovery one

**Comment by unchained-za** [comment]
The way I understand it is that the first report supplies the correct engineId, time and boots, which must then be used in the get-request for validation.

**Comment by unchained-za** [comment]
The only other question: are the engineIds on both hosts valid and unique?

**Comment by gavinaiken** [comment]
That's not how the spec seems to have it: https://github.com/markabrahams/node-net-snmp/blob/master/ref/rfc/v3/rfc3414.txt#L1746

I read that as saying it will use 2 requests and 2 reports - the first request is noAuthNoPriv and learns the engine id, then the second request is authenticated and is used to learn the snmpEngineBoots and snmpEngineTime, and that is certainly what I am seeing from this device. The command line net-snmp tools are handling it, so it looks like this library is doing something wrong.

**Comment by gavinaiken** [comment]
> The only other question: are the engineIds on both hosts valid and unique?

Yes

**Comment by unchained-za** [comment]
Ok, I see what you mean. It's been a couple of months since I've actually looked at packet captures for SNMPv3, but I can't remember seeing anything similar except with a real problem.

**Comment by gavinaiken** [comment]
I have a very simple patch which fixes the issue for me on this device at least. Will create a PR for review...

**Comment by markabrahams** [comment]
@gavinaiken - great work to isolate the problem here.

Yes, I find that a weird part of the spec.

The Net-SNMP agent includes msgAuthoritativeEngineBoots and msgAuthoritativeEngineTime in the initial report PDU, effectively collapsing the authoritative engine ID discovery and time synchronisation into a single report PDU.  This approach is more efficient and I don't see a down side.  The standard states that the discovery process *should* (not *must*) establish time synchronisation exchange.  It then states how this *may* (not *must*) occur i.e. with a second report PDU.  As I recall, I ignored this suggested approach at the time of implementing, as I didn't see the need with the Net-SNMP behaviour I was testing against - a downside of a limited testing pool.  And it was a should/may not a must.

Having said all of that, obviously Cisco (and probably others) are following that approach, and so it's obviously good to accommodate!

Also, thanks heaps @gavinaiken for the patch - I'll review this with a view to merging shortly.

**Comment by markabrahams** [comment]
Merged a slightly modified #66 into master and released in v2.5.5 of the npm.

@gavinaiken - if you're able to test the new version and verify it still works for your case, that would be great.  It should do, as my changes were very small, but then again I don't have anything to test this condition on.

@dattatelite - if you can test the new version to see if it fixes your problem as well, that would be great thanks.

**Comment by gavinaiken** [comment]
Definitely seems more efficient to do engine ID discovery and time synchronisation in a single report PDU. The way these Cisco devices do it, there is an overhead of 4 packets / 2 round trips before you even get to ask for the OIDs you wanted in the first place. We have some code which creates a lot of sessions to get various OIDs (with v2c), if we switch to v3 that will be a lot of extra packets, so we're looking at changing the code to use a single session instead.

Anyway - testing the newly released version shortly...

**Comment by markabrahams** [comment]
Yep - agreed 100%!  My feeling is that the SNMPv3 discovery mechanism was a bit of a miss from the protocol designers, although I appreciate their work and attention to security matters.  A significant SNMP use-case is the NMS trying to squeeze a poll of the entire network into a 5 minute polling interval.  To have a up to a 200% v3 overhead with as compared with v2c is a hefty price to pay for the extra security afforded by the discovery mechanism.  The vast majority of use cases I know of operate in a secured management network, and the extra round-trip burden of v3 security is a significant steer back to the unencrypted, unauthenticated bad old days of v2c.  Sorry - rant over :-)

**Comment by gavinaiken** [comment]
That new release version is working fine with my 3 test devices 👍 

Soon rolling out to a bunch more devices, hope that goes smoothly now...

**Comment by markabrahams** [comment]
Thanks for confirming that @gavinaiken - and thanks again for the patch - I never could have found that without a device doing the double report.

**Comment by unchained-za** [comment]
Thanks from me as well, I haven't run into one of those yet, although we mostly monitor Cisco devices. Our node implementation is however still very recent and only tested on a few SNMPv3 hosts.

**Comment by dattatelite** [comment]
@markabrahams I tested it out with 1. MD5 DES 2. SHA DES. Both seem to work fine.👍
Thank you very much.
And Thank you @gavinaiken and @unchained-za.

Although there seems to be an issue with AES 128 (TypeError: Cannot read property 'encryptPdu' of undefined.) We can take this up elsewhere.
