### ISSUE TITLE
SNMP Agent Values not Updating after few days

### ISSUE THREAD

**Issue by ernestclyde** [markabrahams/node-net-snmp#65]
Good day,
Currently i have created an app which monitor some api then send the values using ipc to another app (snmp agent) which register values to 4 table providers and have an index around 2000.
this is the code for updating/registering the value and index
`try{mib.setTableSingleCell ('Group', 2, [index], name)}
				catch(error){
					switch(error.message.toLowerCase()){
						//no items in table
						case 'no mib provider registered for group':
							mib.addTableRow ('Group', [index, name]);
						break
						//not found
						case `cannot read property 'getinstancenodefortablerowindex' of undefined`:
							mib.addTableRow ('Group', [index, name]);
						break
						default:
							console.log(error.message)
							break
					}
				}`

i found out every 2 or 3 days that the table no longer updates the values and saw nothing on cli

**Comment by ernestclyde** [comment]
Hello thank you for creating this snmp agent for node.

Sorry for not being active in the past month

when this problem occurs i always restart the agent and also see nothing on terminal, what information do you need so i can give it to you

**Comment by markabrahams** [comment]
Please provide:
- a mib.dump() of the table before making the mib.addTableRow call that fails to add the row
- the parameters for the mib.addTableRow call that fails to add the row
- a mib.dump() of the table after the mib.addTableRow call that fails to add the row

**Comment by ernestclyde** [comment]
Cant reproduce on new version
