### ISSUE TITLE
why I can not fetch a attable in example code snmp-agent.js by snmptable ?

### ISSUE THREAD

**Issue by 1000copy** [markabrahams/node-net-snmp#67]
I 'd like to run agent 

     node example/snmp-agent.js

then visit the SNMP agent by snmptable command:

    snmptable -v 2c -c public  10.27.10.80 .1.3.6.1.2.1.2.2      

I expect a table output ,but actually ,I gotten a output here:

     End of MIB
     IF-MIB::ifTable: No entries 

What can I do for my purpose?
the source code I run is newest from github repo.
thanks.

**Comment by markabrahams** [comment]
Hi @1000copy - thanks for submitting this.

Your problem was due to a bug in the library when handling GetNext OIDs not in the MIB tree.

I've fixed this problem in master now, and the fix is released in v2.5.6 of the npm.

**Comment by 1000copy** [comment]
Great!
