### ISSUE TITLE
ModuleStore.loadFromFile does not handle paths correctly

### ISSUE THREAD

**Issue by nova706** [markabrahams/node-net-snmp#74]
In order to load from a file, the path must either be relative from the file directory or start with '/'. This makes it impossible to load with absolute paths (C:/tmp/mymib.mib).

**Comment by nova706** [comment]
Though my comment points this out, I’ll clarify this is an issue on Windows since paths start with a drive letter.

**Comment by markabrahams** [comment]
Thanks for that @nova706  - have merged #75 into master and released in v2.5.9 of the npm.

**Comment by nova706** [comment]
@markabrahams No problem, thanks for the quick response!
