### ISSUE TITLE
Can not close receiver.

### ISSUE THREAD

**Issue by tuanptit** [markabrahams/node-net-snmp#80]
I created a `receiver` to receive a trap like this:  

`var receiver = snmp.createReceiver (options, callback);`

It receive trap ok but now I  `close` that  `receiver` like this:

`receiver.close()`.

But I receive an error in server: 

`TypeError: this.listener.close is not a function`

I google search but did not see any thing about receiver.

**Comment by markabrahams** [comment]
Hi @tuanptit - thanks for reporting this.

I've fixed this in master now and published in v2.5.11 of the npm.
