### ISSUE TITLE
Is there a way of telling the lib to not parse the value of an OctetString?

### ISSUE THREAD

**Issue by AndrelsFlor** [markabrahams/node-net-snmp#84]
The piece of equipment I'm trying to integrate with requires that I send a mac as "plain text" via SNMP to it, however, the lib seems to parse it into a "Buffered" string before actually sending it. Is there a way to bypass this without changing the lib's code?

**Comment by markabrahams** [comment]
Hi @AndrelsFlor - please post your code for this - thanks.

**Comment by AndrelsFlor** [comment]
Hi. I'm sorry, it was a mistake in another part of the code that ended up not being related to the lib at all. I'm closing the issue. Thanks, anyway!

**Comment by markabrahams** [comment]
No problems @AndrelsFlor - thanks for following up.
