### ISSUE TITLE
Unable to see the `value` being set in the MibRequest

### ISSUE THREAD

**Issue by chris-peerman** [markabrahams/node-net-snmp#85]
I have registered a provider with `mib.registerProvider(provider)` and I wanted to do operations based on the value being passed in, so I've registered a handler for the provider. However, the `MibRequest` object gives me the `operation`, `providerNode`, `instanceNode` and the `oid` but does not give me the actual value being set.

Is it possible to have the `MibRequest` object also contain the value being set? Or is there another way of doing this?

I'm currently working out how to delete from a table when the

**Comment by markabrahams** [comment]
Thanks @chris-peerman for raising this.  Yeah - that's pretty important info for a SetRequest!

I've added setValue and setType fields in the MibRequest object presented for a SetRequest (these two fields are not present for the MibRequest object for other PDU types).

Updated in master and published in version 2.6.3 of the npm.
