### ISSUE TITLE
SNMP Error when connecting to multiple servers (Netdata)

### ISSUE THREAD

**Issue by kevinp1005** [markabrahams/node-net-snmp#89]
![Screen Shot 2020-05-11 at 12 18 11](https://user-images.githubusercontent.com/25806608/81772954-cfb9c200-9519-11ea-9351-61df4f5dbac7.png)

I got this error when trying to connect to multiple SNMP devices (more than 100 devices).
But if i just put this device in its own in the config file, it works.

**Comment by markabrahams** [comment]
Hi @kevinp1005 - this is not a node-net-snmp library error.  If it is a Netdata error, the appropriate place to raise this is with the NetData project.

See the CONTRIBUTING.md guidelines for submitting bug reports against this library, particularly:
**Isolate the problem to the library** &mdash; Make sure that the code
in the node-net-snmp library is _definitely_ responsible for the issue.
