### ISSUE TITLE
ReferenceError: cipher is not defined - SNMPv3 MD5 DES

### ISSUE THREAD

**Issue by gmicek-liongard** [markabrahams/node-net-snmp#92]
I'm getting the following traceback when running SNMPv3 on a windows host:

authPriv
snmp.AuthProtocols.md5
snmp.PrivProtocols.des

```
ReferenceError: cipher is not defined
    at Encryption.encryptPduDes (C:\<redacted>\node_modules\net-snmp\index.js:1003:10)
    at Object.Encryption.encryptPdu (C:\<redacted>\node_modules\net-snmp\index.js:936:10)
    at Message.toBufferV3 (C:\<redacted>\node_modules\net-snmp\index.js:1227:35)
    at Message.toBuffer (C:\<redacted>\node_modules\net-snmp\index.js:1140:17)
    at Session.send (C:\<redacted>\node_modules\net-snmp\index.js:1916:30)
    at Session.sendV3Req (C:\<redacted>\node_modules\net-snmp\index.js:2340:8)
    at Session.onMsg (C:\<redacted>\node_modules\net-snmp\index.js:1857:16)
    at emitTwo (events.js:106:13)
    at Socket.emit (events.js:191:7)
    at UDP.onMessage (dgram.js:561:8)

```

`"net-snmp": "^2.6.4",`

The line numbers above in the traceback may not directly line up because I had to run a babel step (per the PR I sent separately https://github.com/markabrahams/node-net-snmp/pull/87).

Any ideas? Thanks!

**Comment by markabrahams** [comment]
Hi @gmicek-liongard - confirm that your build of Node.js has crypto support:

https://nodejs.org/api/crypto.html#crypto_determining_if_crypto_support_is_unavailable

**Comment by gmicek-liongard** [comment]
Hi @markabrahams 
```
$ node
> const crypto = require('crypto')
undefined
> .exit
$ nvm ls 
->       v6.9.5
        v8.16.0
       v10.18.1
         system
default -> 10.18.1 (-> v10.18.1)
node -> stable (-> v10.18.1) (default)
stable -> 10.18 (-> v10.18.1) (default)
iojs -> N/A (default)
unstable -> N/A (default)
lts/* -> lts/erbium (-> N/A)
lts/argon -> v4.9.1 (-> N/A)
lts/boron -> v6.17.1 (-> N/A)
lts/carbon -> v8.17.0 (-> N/A)
lts/dubnium -> v10.20.0 (-> N/A)
lts/erbium -> v12.16.2 (-> N/A)
```
or per the doc you linked:
```
$ node
> let crypto;
undefined
> try {
...   crypto = require('crypto');
... } catch (err) {
...   console.log('crypto support is disabled!');
... }
{ DEFAULT_ENCODING: 'buffer',
  constants: 
   { SSL_OP_ALL: 2147486719,
... ( rest of output omitted )
```
Yep crypto looks good here. I think the AES cipher is working, but I'm not 100% sure. I need to fiddle with the test environment a bit to confirm AES is ok.
(SNMP v2 works just fine btw, I don't believe there's any cipher work in that codepath though but just an fyi)

If I find some more info on what might be going on, I'll post it here

**Comment by markabrahams** [comment]
Hi @gmicek-liongard - please post a minimal reproduction that others can copy-paste to test on their Windows or non-Windows setup - which might help to identify if any patterns emerge.

Also, post your results of testing in other environments (OS versions, node versions, etc.), if you have access to any.

**Comment by gmicek-liongard** [comment]
Sounds good Mark, will do. It'll take me some time to figure out how to get that narrowed down to something concise, but then I will

**Comment by gmicek-liongard** [comment]
It had to do with some variable initializations and the transpiler I was using (babel). See https://github.com/markabrahams/node-net-snmp/pull/110
