### ISSUE TITLE
Ability to Register Providers and Table Rows before snmp agent creation

### ISSUE THREAD

**Issue by ernestclyde** [markabrahams/node-net-snmp#94]
hello,
is it possible to register providers and insert table rows before snmp agent creation?

**Comment by markabrahams** [comment]
Hi @ernestclyde - this isn't possible at the moment, but this isn't a difficult enhancement, so I will add this to the API.

**Comment by markabrahams** [comment]
HI @ernestclyde - I've added this enhancement to master and published it in v2.8.0 of the npm.

The README.md has updated usage documentation for the feature, but in short, snmp.createMib () creates a Mib instance separate from an agent, and then snmp.createAgent takes an optional third "mib" parameter so you can supply your pre-created Mib to the agent.

var mib = snmp.createMib ();
// add providers, add scalar/table data e.g.
// mib.registerProvider (someTableProvider);
// mib.addTableRow (cell1, cell2, cell3);
...
// when mib has been initialized, pass the mib to the createAgent call
var agent = snmp.createAgent (someOptions, someCallback, mib);

You can also swap out the agent's Mib instance mid-flight at any time with a new one:
agent.setMib (someNewMibInstance);
